敵対モンスターの友好モンスター召喚時のバグについて
hengband/hengband pull request #1268
Opened 2021-07-22 13:48 UTC by Slimebreath6078

#1241 
モンスター生成処理の際、友好化の条件が「モンスターが友好的な特性を持つ場合、"または"召喚主が友好、または強制的に友好にする場合」という処理だったため、モンスターが友好の特性を持つかどうかの判定を自然生成（whoが0）の時にのみするように変更するのはいかがでしょうか。
これであれば召喚主が敵対している場合は普段友好なモンスターも召喚された際に敵対して生成されます。

2021-07-22 13:54 UTC, sikabane-works commented
ありがとうございます。これでありだと思うので別件勧めているので確認次第Approveとマージさせていただきます。

2021-07-22 14:06 UTC, Slimebreath6078 commented
承知いたしました。ご対応ありがとうございます。

2021-07-23 06:10 UTC, Slimebreath6078 commented
昨日出した修正案について改善を出そうとしましたが、自動生成でも敵対してしまうコードだったので取り下げます。すみません。

2021-07-23 07:12 UTC, Slimebreath6078 commented
自動じゃなくて自然だった

2021-07-23 11:50 UTC, sikabane-works commented
今の時点でそれも改善されているということでしょうか？とりあえずこちらでも取り掛かれるのでレビューします。

2021-07-23 12:03 UTC, Slimebreath6078 commented
昨日の修正案の時点で召喚のバグについては問題ないです、自然生成の時に関しては以前のコードの時点で友好フラグの敵は友好状態になります。
しかしデバッグの敵生成に関してコメントアウトに「敵対的に召喚」とあるのに友好フラグ持ちは友好状態で生成されるのが気になりまして、今日出そうとした改善はそこら辺も改善できるような案を出そうとしました。

2021-07-23 12:07 UTC, Slimebreath6078 commented
一応デバッグの敵生成に関しては別の案が思い浮かびましたが、そちらについては単に「デバッグの敵生成が仕様通りに動作しない問題の修正」で、このプルリクエストとは別件なのでここではなく新しいリクエストでやった方がよさそうな感じはあります

2021-07-23 12:16 UTC, sikabane-works commented
ではそれが出来次第またforce-pushしてらえればありがたいです。よろしくお願いします。

2021-07-23 12:23 UTC, Slimebreath6078 commented
承知いたしました。
第一候補の案が昨日のコードの変更を適用すること前提なので、適用されるか否かが決まった際にそれに合った案を出します。

2021-07-25 08:48 UTC, sikabane-works commented
とりあえずAlpha33に回します。

2021-07-25 13:04 UTC, Slimebreath6078 commented
承知いたしました。
念のため申し上げておきますが、レビューやマージなどは最初の変更の方でお願いいたします。
システム的に難しいなどあれば再プッシュいたします。

2021-07-25 13:05 UTC, sikabane-works commented
了解です。

2021-07-31 10:38 UTC, sikabane-works approved these changes
遅れてすみません、前後で改善を確認しました。マージどうぞ。

2021-07-31 10:40 UTC, sikabane-works requested changes
と思いましたがすみません、警告が出たのでテストでマージ不可な状態になっています。
恐らく修正箇所以下のように()で優先順位を明確にしないといけません。
`else if (((r_ptr->flags7 & RF7_FRIENDLY) && is_friendly_idx(player_ptr, who)) || (mode & PM_FORCE_FRIENDLY)) {`

2021-07-31 11:09 UTC, Slimebreath6078 commented
直しました。すみません。

else if ((r_ptr->flags7 & RF7_FRIENDLY) && is_friendly_idx(player_ptr, who)) || (mode & PM_FORCE_FRIENDLY))

だとFRIENDLYフラグの存在が実質消えてしまうので
（自然生成はwhoが0なのでis_friendly_idx(player_ptr, who)がfalseを返す）

else if ((!who && (r_ptr->flags7 & RF7_FRIENDLY)) || is_friendly_idx(player_ptr, who) || (mode & PM_FORCE_FRIENDLY))

とします。
これでいかがでしょうか？

2021-07-31 11:13 UTC, Slimebreath6078 commented
すみません、コードブロックを入れるのを忘れておりました。

`else if ((r_ptr->flags7 & RF7_FRIENDLY) && is_friendly_idx(player_ptr, who)) || (mode & PM_FORCE_FRIENDLY)) {`

だとFRIENDLYフラグの存在が実質消えてしまうので
（自然生成はwhoが0なので`is_friendly_idx(player_ptr, who)`がfalseを返す）

`else if ((!who && (r_ptr->flags7 & RF7_FRIENDLY)) || is_friendly_idx(player_ptr, who) || (mode & PM_FORCE_FRIENDLY)) {`

とします。
差し支えなければお願いいたします。

2021-07-31 12:13 UTC, sikabane-works approved these changes
自動テストもOK出ました。お疲れさまでした。

2021-07-31 12:42 UTC, Slimebreath6078 commented
お手数をかけてすみませんでした。ありがとうございます。

2021-07-31 12:42 UTC, merged

2021-07-31 12:44 UTC, sikabane-works commented
こちらこそ、ありがとうございます。この調子で何か気になれば続けてもらえれば幸いです。