デバッグのモンスター生成についてコメント側を合わせる
hengband/hengband pull request #1305
Opened 2021-08-02 09:49 UTC by Slimebreath6078

#1302

こっちの方がデバッグ上の「モンスター生成」とも合ってるし、使い勝手もこっちが良さそうなのでこちらから

2021-08-02 09:50 UTC, Slimebreath6078 commented
あっ、友好化が元の状態に戻っちまってるな…一旦なしで

2021-08-02 10:19 UTC, Slimebreath6078 commented
すみません、上書きし直したのでプルリクエスト開き直してみます

2021-08-02 10:30 UTC, Hourier requested changes
対応お疲れさまです
処理そのものは問題なさそうですが、2点コメントします
- whoはbool型でなく整数型なので、「!who」よりも「(who == 0)」が好ましいです
- ビットフラグの部分は、bit-flags-calculator.h をインクルードして、any_bits(r_ptr->flags7, RF7_FRIENDLY)として下さい

2021-08-02 10:35 UTC, Slimebreath6078 commented
承知いたしました。今から修正いたします

2021-08-02 11:29 UTC, Hourier reviewed
もう1箇所、「(mode & PM_FORCE_FRIENDLY)」のところも「any_bits(...)」に差し替えお願いします

2021-08-02 12:29 UTC, Slimebreath6078 commented
承知いたしました。同ファイル内に類似する箇所があった場合そこも修正しておきます。

2021-08-02 12:34 UTC, Slimebreath6078 commented
いや、それは別のプルリクエストでやるべきか…とりあえず一旦言われた部分だけ直します

2021-08-02 12:48 UTC, Hourier submitted a review, later dismissed
対応ありがとうございました
個人的にはあまりこだわりないですが、any_bits() を使うべき箇所は膨大な数に上るので、別チケットに分けても良いかもしれません
Approveします

2021-08-02 13:07 UTC, Slimebreath6078 commented
こちらこそ色々手間かけさせてすみません。テストとかが終わったのを確認次第マージしようと思います

2021-08-02 16:48 UTC, habu1010 commented
何点か問題がありますので、挙げておきます
- コンフリクトが発生しているので、マージするには解消する必要がります。
- BOMが削除されてしまっています。（Visual Studio でUTF-8のソースコードをコンパイルする関係上、BOMが必要です）
- 都度修正を重ねた複数のコミットがありますが、途中のコミット履歴は残す必然性が無いものなので、できれば1つのコミットにsquashするのが好ましいです(参考: https://www.granfairs.com/blog/cto/git-merge-squash)。

2021-08-02 19:21 UTC, Slimebreath6078 commented
粗が多くてすみません
コンフリクトとBOMの解消はいたしましたが、現在squashが解決できていない状態で、squashマージのコマンドを入れると(nothing to squash)と表示されてしまいます

2021-08-03 08:12 UTC, habu1010 commented
この状態からすっきりしたコミットを作るのはやや面倒なので、いっそのこと最終的なソースコードの変更（ https://github.com/hengband/hengband/pull/1305/files ）を反映したコミットを作り直してPull Requestを作成しなおす（あるいは同名ブランチで作ってforce-pushする）ほうが楽かもしれません。

一応現状のコミット履歴から squash merge でコミットを作り直す手順を挙げておくと次のような感じになります。

- 一連のコミットの最終コミット（BOMを戻したコミット）に適当なブランチ名をつける (作業用ブランチ名として仮に work とする)
- 手元のPR用ブランチ( feature/bug_fix_wizard_monster_summon_comment )を削除し、developから同名のブランチを新たに作成しそのブランチをチェックアウトする
- git merge --squash work を実行
- コンフリクトが発生するので解消してからコミット
- feature/bug_fix_wizard_monster_summon_comment を force-push

以上はGitに関するそれなりの理解と習熟が必要なので、最終的な修正分量は少ないこともあり前述の通りコミットを作り直したほうが手っ取り早いかと思います。

2021-08-03 08:45 UTC, Slimebreath6078 commented
調べてみると確かに最終コミットに適当なブランチ名を付けるのは面倒臭そうですね…
皆さんには申し訳ないですが、ここは一旦変更をまとめたコミット一つとプルリクエストを作り直します。

2021-08-03 08:45 UTC, closed without merging