フラグ管理のリファクタリング(one-monster-placer.cpp)
hengband/hengband pull request #1311
Opened 2021-08-05 10:41 UTC by Slimebreath6078

#1307
one-monster-placer.cppのフラグ管理を全部マクロにしました

#1306 
ついでに前回のコメント修正のミスも修正しました（小声）

2021-08-05 10:46 UTC, Hourier requested changes
L64、L85、L279に不要なカッコが付いています
(関数マクロの定義部分でカッコが付いているので二重取り状態)
除去お願いします

2021-08-05 11:00 UTC, Slimebreath6078 commented
すみません。修正いたしました。
あとmergeする際にsquash忘れておりました。重ねてすみません。

2021-08-06 15:09 UTC, Slimebreath6078 commented
mergeする際にsquash忘れてた、じゃ語弊がありすぎる

pushするためのmergeでsquash忘れてた、って言った方が正しいか

2021-08-06 15:11 UTC, Slimebreath6078 commented
とりあえずこちらも待っておりますので、いったんプルリク作り直すなりでまとめた方がよさそうであれば作り直します

2021-08-06 15:14 UTC, Hourier commented
もう2箇所、L376とL378もお願いします
(コメントしたつもりでしたが抜けてました)

2021-08-06 15:26 UTC, Slimebreath6078 commented
すみません、そちらの二重括弧も除去いたしました
確認お願いいたします

2021-08-06 15:39 UTC, Hourier approved these changes
確認しました
対応ありがとうございました
問題ありませんのでApproveします

2021-08-06 21:37 UTC, Slimebreath6078 commented
ありがとうございます。それではマージします。

2021-08-06 21:37 UTC, merged