spells-hex.cpp/h のクラス化＆メソッド分割
hengband/hengband pull request #1482
Opened 2021-09-06 12:05 UTC by Hourier

掲題の通りです
本題はmonap_type にメソッドを定義してクラス化する予定でしたが、その過程で「目には目を」の反撃効果やら反テレポートによる盗み逃げ防止効果やらが見つかりました
monap_type だけクラス化しても片手落ち感が半端なかったのと、eyes_on_eyes() はspell-hex.cpp/h へ移すべきとの思いから、先にこのファイルをクラス化することとしました
中途半端に関数を集めたままほったらかしにされていたのでついでに (というか作業の大半)メソッド分割・改名も行いました
ご確認下さい

2021-09-06 13:07 UTC, habu1010 requested changes
目を通して気づいた点をコメントしました。

2021-09-06 13:07 UTC, habu1010 commented on src/core/player-processor.cpp
> +        auto realm_hex = RealmHex(creature_ptr);
他と同様に RealmHex realm_hex(creature_ptr); でいと思います。
この書き方だと余計なオブジェクトのムーブが発生します。

2021-09-06 13:07 UTC, habu1010 commented on src/spell-realm/spells-hex.cpp
> +    std::vector<int> sp[MAX_KEEP]{};
宣言の仕方がおかしいです。これだと空のvector<int>オブジェクトが4要素ある配列を宣言しています。
std::vector<int> sp(MAX_KEEP);
が正しいと思います。

2021-09-06 13:26 UTC, Hourier commented on src/core/player-processor.cpp
> +        auto realm_hex = RealmHex(creature_ptr);
ここはケアレスミスでした
修正します

2021-09-06 13:27 UTC, Hourier commented on src/spell-realm/spells-hex.cpp
> +    std::vector<int> sp[MAX_KEEP]{};
指摘の通り、ここは要素数を指定すべきでvectorの配列を作りたい訳ではないです
頂いた通りに修正します

2021-09-06 13:28 UTC, Hourier commented on src/spell-realm/spells-hex.cpp
> +bool RealmHex::select_spell_stopping(std::vector<int> *sp, char *out_val, char *choice)
ご指摘の通り、non-nullableな変数は&で定義します

2021-09-06 13:28 UTC, Hourier commented on src/window/main-window-stat-poster.cpp
> +        if (RealmHex(creature_ptr).is_spelling_specific(HEX_BLESS))
先頭で宣言するようにします

2021-09-06 13:29 UTC, Hourier commented on src/spell-realm/spells-hex.cpp
> +{
ここは元からがっちゃんこされていたコードですが、確かに生成と表示は分けるべきですね
コメントの通りに修正します

2021-09-06 14:00 UTC, Hourier commented
修正しました
rebase/force pushしようかとも思いましたが、元々のコードとの兼ね合いと、指摘への反映はなるべくrebaseせずに記録しておきたかったのでそのまま上にコミットを重ねました
ご確認下さい

2021-09-06 14:13 UTC, habu1010 commented on src/spell-realm/spells-hex.cpp
> +void RealmHex::make_spells_list(std::vector<int> &sp)
好みがわかれるかもしれませんが、std::vector<int> sp(MAX_KEEP)はこの関数内で宣言し、std::vector<int> を返すインターフェースにしたほうが明快なように思います。
NRVOによりstd::vectorオブジェクトの無駄なコピーは発生しないはずなので、コピーのオーバーヘッドを考慮する必要もありません。

2021-09-06 14:13 UTC, habu1010 commented on src/spell-realm/spells-hex.cpp
> +    this->make_spells_list(sp);
make_spells_listは select_spell_stoping を呼ぶ前で呼び出し、 select_spell_stopping に作成済みのspを渡すようにするべきだと思います。
また、そうすれば std::vector<int> &sp 引数に const を付けることで select_spell_stopping で sp が変更されることがない事を明示できます。

2021-09-06 14:13 UTC, habu1010 commented on src/spell-realm/spells-hex.cpp
> +constexpr int max_spells = 32;
変愚蛮怒のコーディング規約として明確に定められているわけではありませんが、定数はすべて大文字にしておいたほうが無難だと思います。

2021-09-06 14:13 UTC, habu1010 commented on src/spell-realm/spells-hex.cpp
> +{
display_spells_listに渡していた引数spを削除していますが、先に生成したspを渡せば、

```c++
for (auto spell = 0; spell < max_spells; spell++)
```

の部分を

```c++
for (auto spell : sp)
```

のように range-based for にすることができると思います。is_spelling_specifigでチェックしなおす必要もなくなります。

2021-09-06 14:42 UTC, Hourier commented
コメントありがとうございました
今度は比較的単純な修正だったのでforce pushしました
ご確認下さい

2021-09-06 15:09 UTC, habu1010 requested changes
vectorの扱いについてもう1件コメントしておきました。
それから呪術自体の挙動についてですが、呪術ハイメイジの仕様にあまり詳しくないのですがすこしプレイしてみたところすぐ詠唱が中断されたりと、developブランチとはあきらかに異なる挙動をしているようです。
このあたりのデバッグが必要そうです。

2021-09-06 15:09 UTC, habu1010 commented on src/spell-realm/spells-hex.cpp
> +    std::vector<int> spells(MAX_KEEP);
spellsのvectorですが、よく考えると最初からMAX_KEEPを確保する必要はなく、空のvectorを作成してspells.at(n) = spell; のところをpush_backに変えて挿入していけばいいと思います。
逆にそうしないと、あとで range-based for により詠唱中の呪文一覧を表示する時に、無駄な領域の分まで処理されてしまいそうです。

2021-09-07 09:35 UTC, Hourier commented on src/spell-realm/spells-hex.cpp
> +    std::vector<int> spells(MAX_KEEP);
詠唱の中断バグについては解消しました
vectorのpush_backについてですが、よく考えると以下のコードがひたすらコピペで並んでいるので、何とかしたいところです
あっちこっちの引数にするのもナンなので、std::vector<int> をprivate変数に置くのはいかがでしょうか？
```
for (auto spell = 0; spell < MAX_REALM_SPELLS; spell++) {
    if (this->is_spelling_specific(spell)) {
        // 何か処理
    }
}
```

2021-09-07 09:46 UTC, habu1010 commented on src/spell-realm/spells-hex.cpp
> +    std::vector<int> spells(MAX_KEEP);
確かに、クラス内で詠唱中のスペルリストをスキャンするこのループ処理が頻出しているので、コンストラクタで最初に作成詠唱中の呪文リストとしてvectorのプライベート変数を作成しておくのは良いかもしれませんね。
（クラスの用途的に、オブジェクトの生存期間中に詠唱中の呪文リストを更新する必要があるかどうかはちょっとすぐには確認できませんが）

2021-09-07 11:00 UTC, Hourier commented on src/spell-realm/spells-hex.cpp
> +    std::vector<int> spells(MAX_KEEP);
コールチェーンを辿った限りは、呪文リストの更新は本クラスの中では行われないはずです
- 元々stop_one_spell() がコールされない限りは呪文リストが更新されない
- 呼び出し元×2は両方ともユーザ入力1回につき1回しかコールされない (はず、万が一のことがあったら再調査)

また、リスト作成に当たってMAX_KEEPの情報が若干失われたので、「最大4つしか詠唱状態ではないはず」という契約違反時には例外を吐くように加筆しました (誰もcatchしてないですがそれはご愛嬌)
併せてご確認下さい

2021-09-07 11:48 UTC, habu1010 reviewed
大枠では問題なくなったと思います。
かるく動かしてみた感じでも、特におかしな動作はしてなさそうです。
変数名について2点だけコメントしました。

2021-09-07 11:48 UTC, habu1010 commented on src/spell-realm/spells-hex.cpp
> +            this->spells.push_back(spell);
詠唱中の呪文のリストであることを示すため、変数名を casting_spells にしたほうが良いと思います。

2021-09-07 11:48 UTC, habu1010 commented on src/spell-realm/spells-hex.cpp
> +    auto flag = select_spell_stopping(out_val, choice);
変数名が曖昧なので、is_selected 等にしたほうがいいと思います。

2021-09-07 11:54 UTC, Hourier commented
変数名を修正しました
ご確認下さい

2021-09-07 11:59 UTC, habu1010 approved these changes
対応お疲れさまでした。コード上はひとまず問題なさそうになったので、Approveします。
今後呪術ハイメイジの細かい動作でおかしな点が出たら別途修正していくということで。

2021-09-07 12:17 UTC, habu1010 approved these changes

2021-09-07 12:18 UTC, merged

2021-09-07 12:18 UTC, Hourier commented
長期間のご対応ありがとうございました！