アイテムの仕様に関する exe_hoge() 関数をhoge-execution.cpp/h に移しクラス化した
hengband/hengband pull request #1648
Opened 2021-09-26 02:35 UTC by Hourier

#553 の前段作業です
そもそも仕様実現に当たって既存の設計がグダグダ過ぎたのと、朦朧による失率の計算を一元化するのを合わせて実施しました
ご確認下さい

2021-09-27 10:18 UTC, habu1010 requested changes
お手数ですがこちらもリベースをお願いします。

2021-09-27 11:10 UTC, Hourier commented
歴史を修正してforce pushしました
ご確認下さい

2021-09-29 13:32 UTC, habu1010 commented on src/object-use/zaprod-execution.cpp
> +        success = randint0(fail * 2) >= chance;
成功/失敗の真偽が以前と反転しています。

2021-09-29 13:39 UTC, Hourier commented
確認ありがとうございました
修正の上force pushしました
ご確認下さい

2021-09-29 14:02 UTC, habu1010 approved these changes
ひとまず他に動作でおかしいところには気づかなかったので、Approveします。

2021-09-29 14:04 UTC, merged

2021-09-29 14:04 UTC, Hourier commented
確認ありがとうございました！