SourceTrailの解析 (clangベース)でエラーが出た箇所を修正した
hengband/hengband pull request #1660
Opened 2021-09-26 14:30 UTC by Hourier

小さな置換なのでチケットはなしで
掲題の件、久しぶりに起動して解析したら2ファイルでエラーが出ました
それを修正しただけのコミットです
ご確認下さい
\# concptrではなくconst char\* を使ったのは今後の型エイリアス削減のため

2021-09-27 10:16 UTC, habu1010 requested changes
内容は問題ありませんが、 #1666 の事情により例外的にdevelopを差し戻したのでリベースをお願いします。

2021-09-27 10:50 UTC, Hourier commented
ブランチの歴史を修正してforce pushしました
ご確認下さい

2021-09-27 10:55 UTC, habu1010 commented on src/view/display-util.cpp
>  } disp_player_line[]
修正と直接関係ありませんが、この際なので disp_player_line を constexpr にしてしまってはどうでしょうか。

2021-09-27 10:57 UTC, Hourier commented on src/view/display-util.cpp
>  } disp_player_line[]
OKです
他ブランチの歴史を修正し終えたら取り掛かります

2021-09-27 12:39 UTC, Hourier commented
構造体の宣言と配列 (vector)を分離し、更に無名名前空間で修飾しました
ついでに日英の表記を\_() で統一しました
ご確認下さい

2021-09-28 11:11 UTC, habu1010 approved these changes
問題ないと思います。Approveします。

2021-09-28 11:12 UTC, merged

2021-09-28 11:12 UTC, Hourier commented
確認ありがとうございました！