モンスターのフラグをまとめる（動作（習性？））
hengband/hengband pull request #2049
Opened 2022-01-31 11:27 UTC by Slimebreath6078

Resolved #1951 
一旦、定義名や分け方がこれでいいか確認のためDraftで出します

2022-01-31 11:29 UTC, Slimebreath6078 commented
このPR、#208 にも繋がってそうだけどどうなのだろうか（繋がるならそっちもResolved でリンクする）

2022-01-31 11:35 UTC, habu1010 reviewed
フラグの分け方は私からは特に異議は無いですが、変更点が埋もれてしまうので整形コミットは分けたほうが良いです。

2022-01-31 11:42 UTC, Hourier commented
上に同感です
ところでこのフラグは、このPR時点ではまだ全く使われていないということでしょうか？
使うところまで (↓くらい)作業してしまっても問題ありません
https://github.com/hengband/hengband/pull/1791

2022-01-31 12:18 UTC, Slimebreath6078 commented
承知いたしました
実装までやったらpushいたします

2022-01-31 12:19 UTC, Hourier commented
よろしくお願いします
ちなみに他のフラグ (ONLY\_ITEM等)がどうなっているのか確認したいので、該当するSBbandのチケットURLも張り付けてもらえますか？

2022-01-31 12:35 UTC, Slimebreath6078 commented
以下、他フラグについてのチケットのURLです

[耐性 #79](https://github.com/Slimebreath6078/SBband/pull/79)
[種族・徳 #81](https://github.com/Slimebreath6078/SBband/pull/81)
[ドロップ #93](https://github.com/Slimebreath6078/SBband/pull/93)
[見た目 #95](https://github.com/Slimebreath6078/SBband/pull/95)
[明かり・闇の範囲 #96](https://github.com/Slimebreath6078/SBband/pull/96)
[出現上限 #114](https://github.com/Slimebreath6078/SBband/pull/114)
[地形関連 #115](https://github.com/Slimebreath6078/SBband/pull/115)
[生息地(荒野関連) #127](https://github.com/Slimebreath6078/SBband/pull/127)
[性別 #129](https://github.com/Slimebreath6078/SBband/pull/129)
[その他 #117](https://github.com/Slimebreath6078/SBband/pull/117)

2022-02-04 16:38 UTC, Slimebreath6078 commented
実装部分まで書き終わりました

2022-02-05 01:59 UTC, Hourier requested changes
確認しました
内容は問題ないと思いますが文法面でいくつかコメントしました
先日話した、他作業との兼ね合いで遅延している箇所ですが、以下のクラス群です
お手数ですが併せて修正してもらえると助かります

item-loader-version-types.h
```c
enum class ItemLoaderVersionType {
	LOAD10, // ここを50くらいに引き上げる
	LOAD11, // こっちは51
};
```

monster-loader-version-types.h
同上
```
enum class MonsterLoaderVersionType {
    LOAD10,
    LOAD11,
};
```

item-loader-factory.cpp
```c
ItemLoaderVersionType ItemLoaderFactory::get_version()
{
    if (loading_savefile_version_is_older_than(11)) { // ここを51くらいに引き上げておく
        return ItemLoaderVersionType::LOAD10;
    } else {
        return ItemLoaderVersionType::LOAD11;
    }
}
```

2022-02-05 01:59 UTC, Hourier commented on src/dungeon/dungeon.h
> +    EnumClassFlagGroup<MonraceBehaviorType> m_race_behavior_flags;
この2つ、「m\_」はメンバー変数のmではなくモンスターのmであり紛らわしいので、「mon\_」に改名願います

2022-02-05 01:59 UTC, Hourier commented on src/lore/lore-util.h
> +    EnumClassFlagGroup<MonraceBehaviorType> race_behavior_flags;
(ついでですが) C++風の宣言に変えて下さい
Before
```c
typedef struct hoge_type {
} hoge;
```

After
```c
struct hoge {
};
```

2022-02-05 01:59 UTC, Hourier commented on src/monster/monster-processor-util.h
>  typedef struct turn_flags {
C++風に宣言変更

2022-02-05 01:59 UTC, Hourier commented on src/monster/monster-processor-util.h
>  typedef struct old_race_flags {
C++風に宣言変更

2022-02-05 01:59 UTC, Hourier commented on src/target/target-getter.cpp
> +        } else if (r_ptr->race_behavior_flags.has(MonraceBehaviorType::RAND_MOVE_50) && r_ptr->race_behavior_flags.has(MonraceBehaviorType::RAND_MOVE_25) && (randint0(100) < 50))
まとめて良さそうです
```
r_ptr->race_behavior_flags.has_all_of( { MonraceBehaviorType::RAND_MOVE_50, MonraceBehaviorType::RAND_MOVE_25 } )
```

2022-02-05 01:59 UTC, Hourier commented on src/view/display-lore.cpp
> +    if (lore_ptr->race_behavior_flags.has_not(MonraceBehaviorType::RAND_MOVE_50) && lore_ptr->race_behavior_flags.has_not(MonraceBehaviorType::RAND_MOVE_25))
「指定されたフラグを全て持っていない」なので、以下と等価です
```
!lore_ptr->race_behavior_flags.has_all_of( { MonraceBehaviorType::RAND_MOVE_50, MonraceBehaviorType::RAND_MOVE_25 } )
```

2022-02-05 02:09 UTC, dis- commented on src/view/display-lore.cpp
> +    if (lore_ptr->race_behavior_flags.has_not(MonraceBehaviorType::RAND_MOVE_50) && lore_ptr->race_behavior_flags.has_not(MonraceBehaviorType::RAND_MOVE_25))
!～.has_all_of よりも ～.has_none_of を使うべきですね。
```suggestion
   lore_ptr->race_behavior_flags.has_none_of( { MonraceBehaviorType::RAND_MOVE_50, MonraceBehaviorType::RAND_MOVE_25 } )
```

2022-02-05 02:12 UTC, Hourier commented on src/view/display-lore.cpp
> +    if (lore_ptr->race_behavior_flags.has_not(MonraceBehaviorType::RAND_MOVE_50) && lore_ptr->race_behavior_flags.has_not(MonraceBehaviorType::RAND_MOVE_25))
確かにその通りですね
FlagGroupは本当に便利ですな

2022-02-05 02:13 UTC, habu1010 commented on src/view/display-lore.cpp
> +    if (lore_ptr->race_behavior_flags.has_not(MonraceBehaviorType::RAND_MOVE_50) && lore_ptr->race_behavior_flags.has_not(MonraceBehaviorType::RAND_MOVE_25))
ついでにいうと元の条件と同義なのは !～.has_any_of ですね。（実際FlagGroupクラスのhas_none_ofは!has_any_ofで実装されています）

2022-02-05 10:27 UTC, Slimebreath6078 commented on src/target/target-getter.cpp
> +        } else if (r_ptr->race_behavior_flags.has(MonraceBehaviorType::RAND_MOVE_50) && r_ptr->race_behavior_flags.has(MonraceBehaviorType::RAND_MOVE_25) && (randint0(100) < 50))
今思ったけどこの部分75%で不規則のはずなのになぜ50%なんだろう…
ついでに直してしまってよろしいでしょうか？

2022-02-05 10:28 UTC, Slimebreath6078 commented on src/target/target-getter.cpp
> +        } else if (r_ptr->race_behavior_flags.has(MonraceBehaviorType::RAND_MOVE_50) && r_ptr->race_behavior_flags.has(MonraceBehaviorType::RAND_MOVE_25) && (randint0(100) < 50))
いや、これ騎乗のやつか

2022-02-05 11:51 UTC, Slimebreath6078 commented on src/dungeon/dungeon.h
> +    EnumClassFlagGroup<MonraceBehaviorType> m_race_behavior_flags;
mon_***_flagsに改名いたしました

2022-02-05 11:51 UTC, Slimebreath6078 commented on src/lore/lore-util.h
> +    EnumClassFlagGroup<MonraceBehaviorType> race_behavior_flags;
typedefがない形式に合わせました

2022-02-05 11:51 UTC, Slimebreath6078 commented on src/monster/monster-processor-util.h
>  typedef struct turn_flags {
typedefがない形式に合わせました

2022-02-05 11:51 UTC, Slimebreath6078 commented on src/monster/monster-processor-util.h
>  typedef struct old_race_flags {
typedefがない形式に合わせました

2022-02-05 11:51 UTC, Slimebreath6078 commented on src/target/target-getter.cpp
> +        } else if (r_ptr->race_behavior_flags.has(MonraceBehaviorType::RAND_MOVE_50) && r_ptr->race_behavior_flags.has(MonraceBehaviorType::RAND_MOVE_25) && (randint0(100) < 50))
has_all_ofでまとめました

2022-02-05 11:52 UTC, Slimebreath6078 commented on src/view/display-lore.cpp
> +    if (lore_ptr->race_behavior_flags.has_not(MonraceBehaviorType::RAND_MOVE_50) && lore_ptr->race_behavior_flags.has_not(MonraceBehaviorType::RAND_MOVE_25))
has_none_ofでまとめました

2022-02-05 11:53 UTC, Slimebreath6078 reviewed
ご指摘いただいた内容を修正し、フラグの型・インスタンス共に命名をオーラフラグを参考に統一いたしました
実装部分まで終わったのでReady for reviewにいたします

2022-02-05 12:07 UTC, Hourier approved these changes
対応お疲れ様でした
内容確認しました
追加の指摘はありません
Approveします

2022-02-05 14:53 UTC, Slimebreath6078 commented
ご確認ありがとうございました

2022-02-05 14:53 UTC, merged