[fix][implement]虚無・深淵属性周りの不具合修正とモンスターの魔法実装
hengband/hengband pull request #2080
Opened 2022-02-05 07:46 UTC by daradarach

#2076 
#2077
を修正をした上で、モンスターの魔法に虚無・深淵のボルト・ボール・ブレスを追加。
使い手のモンスターを2種新規実装+既存モンスターへ追加1種。
バランスの問題もあろうかと思うので既存モンスターへの追加範囲はごく限定的とした。

追加・更新した処理のに対する整形 #2027 は別途PRを出すものとして本PRには含めていない

2022-02-05 15:57 UTC, sikabane-works reviewed
モンスター調整１種、新規２種確認

2022-02-05 16:05 UTC, sikabane-works reviewed
AbilityMaskは妥当と判断。

2022-02-05 16:05 UTC, sikabane-works commented on src/blue-magic/blue-magic-breath.cpp
> +    msg_print(_("分解のブレスを吐いた。", "You breathe abyss."));
ここ深淵のブレスが分解なっています。

2022-02-05 16:05 UTC, sikabane-works commented on src/blue-magic/blue-magic-breath.cpp
> + */
虚無のブレス自体はラーニング、利用確認。

2022-02-05 16:18 UTC, sikabane-works commented
ものまねもブレス２種確認。

2022-02-05 16:28 UTC, sikabane-works commented
６種のモンスターからの行動、青魔導士のラーニングと利用、ものまね師のまね確認しました。日本語表記のミスだけ修正お願いします。

2022-02-05 20:39 UTC, daradarach commented on src/blue-magic/blue-magic-breath.cpp
> +    msg_print(_("分解のブレスを吐いた。", "You breathe abyss."));
確認ありがとうございます。直してコミットします

2022-02-06 00:57 UTC, sikabane-works submitted a review, later dismissed
お疲れ様です。Approveします。

2022-02-06 00:59 UTC, Hourier requested changes
確認しました
deskullさんとは違う観点でコメントしました
ご確認下さい

なお全体的に「has\_\*()」で耐性など判定していますが、これらの関数は直感に反して耐性の有無を表すboolではなく装備部位を表すビットフラグを返すようになっています
過去、怪しい挙動が複数報告されているので、お手数ですが現時点では「if(has\_\*())」ではなく「if(has\_\*() != 0)」で判定するようにして下さい

2022-02-06 00:59 UTC, Hourier commented on lib/edit/r_info.txt
> +W:55:1:0:4000:0:0
レアリティ1は高すぎる気がします
2～3が妥当と見えます
(カオス・ボルテックスも同じ問題を抱えているのでこちらは別途調整の余地あり)

2022-02-06 00:59 UTC, Hourier commented on lib/edit/r_info.txt
> +S:BR_VOID
パイプ記号が意味を成していません
1\_IN\_N とその他の魔法は連続して書けます

2022-02-06 00:59 UTC, Hourier commented on lib/edit/r_info.txt
> +F:EMPTY_MIND | BASH_DOOR | POWERFUL |
レアリティに関して同上

2022-02-06 00:59 UTC, Hourier commented on lib/edit/r_info.txt
> +S:1_IN_6 |
パイプによる連結に関して同上

2022-02-06 01:02 UTC, Hourier commented
別件ですが、青魔法系は設計改善の余地が大きいので、この際コードはコピペの方が都合が良く細かい部分はチェックしないものとしました

2022-02-06 01:06 UTC, daradarach commented on lib/edit/r_info.txt
> +W:55:1:0:4000:0:0
2にしておきます

2022-02-06 01:06 UTC, daradarach commented on lib/edit/r_info.txt
> +F:EMPTY_MIND | BASH_DOOR | POWERFUL |
2にしておきます

2022-02-06 01:07 UTC, daradarach commented on lib/edit/r_info.txt
> +S:BR_VOID
1_IN_Nの行に魔法を書いていない方が多く見えますが今後の追加は同じ行に連続を推奨する方向でしょうか？

2022-02-06 01:12 UTC, daradarach commented on lib/edit/r_info.txt
> +S:BR_VOID
Discord上で具体的な指定があったのでその通りに修正しました

2022-02-06 01:12 UTC, daradarach commented on lib/edit/r_info.txt
> +S:1_IN_6 |
Discord上で具体的な指定があったのでその通りに修正しました

2022-02-06 01:12 UTC, Hourier commented on lib/edit/r_info.txt
> +S:BR_VOID
過去、使用率と魔法そのものの間に置いたパイプが効かない仕様ミスがあったためそうなっています
現在は正常に動作するため同じ行に記載して下さい

2022-02-06 01:27 UTC, daradarach commented
has_*()での耐性判定について、全体見渡してもBIT_FLAGSだと思って使っているところが圧倒的に少ないこと、今後直感的に使えることから、寧ろhas_*()の返り値をboolにした方が良いと思います。

2022-02-06 01:36 UTC, Hourier commented
当初打ち立てた仕様が「装備部位を返したい」なので、BIT\_FLAGSを返すための関数として定義されているのは妥当です
設計が狂って「耐性の有無を返すためにも使っている」が現状なので、その修正方針は不適です
ラッパー関数を用意する計画はありますがリソース不足のため全く作業が追いついていません

2022-02-06 01:40 UTC, daradarach commented
なるほど。その使い方があるならラッパー関数を用意する方が良さそうですね。
とりあえず今回追加したコードについては修正しておきました。

2022-02-06 02:12 UTC, Hourier approved these changes
対応お疲れ様でした
確認しました
特に問題ありません
Approveします

2022-02-06 03:15 UTC, merged