モンスターのフラグをまとめる（種族・徳）
hengband/hengband pull request #2164
Opened 2022-02-12 18:13 UTC by Slimebreath6078

Resolved #1951 
Resolved #1436 

コミット数が多いですが、前のとやってることは大体同じです

2022-02-12 18:22 UTC, Slimebreath6078 commented
色々忘れてた部分があるので直します
すみません

2022-02-13 00:59 UTC, Hourier requested changes
対応お疲れ様でした
内容確認しました
h-define.h の件だけご対応下さい (他は↓の通り)

また、effect/ を中心に確認困難な長さのif文が複数ありました
過去の事情ではありますが、一旦変数で受けると見通しが立ちやすくなるかと思います
代表的な箇所に数箇所コメント付けました
しかし範囲が大きい上に今後の共通化で何か支障があるかもしれないので、保留して別チケット対応なり却下なりでもOKです
ご確認下さい

2022-02-13 00:59 UTC, Hourier commented on src/monster-race/monster-kind-mask.cpp
> +const EnumClassFlagGroup<MonsterKindType> good_or_evil = {
「alignment」です (AD&D 初版より)

2022-02-13 00:59 UTC, Hourier commented on src/cmd-action/cmd-pet.cpp
> +        if ((can_attack_with_main_hand(player_ptr) && (empty_hands(player_ptr, false) == EMPTY_HAND_SUB) && player_ptr->inventory_list[INVEN_MAIN_HAND].allow_two_hands_wielding()) || (can_attack_with
長すぎるので一旦変数で受け止めたいです

2022-02-13 00:59 UTC, Hourier commented on src/effect/effect-monster-charm.cpp
> +    if (em_ptr->r_ptr->kind_flags.has(MonsterKindType::UNIQUE) || any_bits(em_ptr->r_ptr->flags1, RF1_QUESTOR) || (em_ptr->r_ptr->flags3 & RF3_NO_CONF) || (em_ptr->r_ptr->level > randint1((em_ptr->da
長すぎるので変数で受け止めたいです

2022-02-13 00:59 UTC, Hourier commented on src/effect/effect-monster-charm.cpp
> +    if (any_bits(em_ptr->r_ptr->flags1, RF1_QUESTOR) || em_ptr->r_ptr->kind_flags.has(MonsterKindType::UNIQUE) || em_ptr->m_ptr->mflag2.has(MonsterConstantFlagType::NOPET) || has_aggravate(player_ptr
長すぎるので変数で受け止めたいです

2022-02-13 00:59 UTC, Hourier commented on src/effect/effect-monster-charm.cpp
> +    if ((inside_quest(floor_ptr->quest_number) && (quest[enum2i(floor_ptr->quest_number)].type == QuestKindType::KILL_ALL) && !is_pet(em_ptr->m_ptr)) || em_ptr->r_ptr->kind_flags.has(MonsterKindType:
長すぎるので変数で受け止めたいです

2022-02-13 00:59 UTC, Hourier commented on src/effect/effect-monster-psi.cpp
> +    bool has_resistance = em_ptr->r_ptr->behavior_flags.has(MonsterBehaviorType::STUPID) || any_bits(em_ptr->r_ptr->flags2, RF2_WEIRD_MIND) || em_ptr->r_ptr->kind_flags.has(MonsterKindType::ANIMAL) |
長すぎるので変数で受け止めたいです

2022-02-13 00:59 UTC, Hourier commented on src/system/h-define.h
>  #ifndef INCLUDED_H_DEFINE_H
ファイルごと消しましょう (Makefile記述、インクルード記述も合わせて)

2022-02-13 12:11 UTC, Slimebreath6078 commented on src/monster-race/monster-kind-mask.cpp
> +const EnumClassFlagGroup<MonsterKindType> good_or_evil = {
alignment_maskに名前を変更しました

2022-02-13 12:15 UTC, Slimebreath6078 reviewed
effect/ 内の長い条件式を変数で受けるようにしました
また、その他ご指摘いただいた箇所も修正いたしました
お手数かけますがご確認お願いいたします

2022-02-13 12:16 UTC, Hourier reviewed
対応お疲れ様です
インクルード周りはもう問題ないと思いますが、追加で1点コメントがあります
ご確認下さい

2022-02-13 12:16 UTC, Hourier commented on src/effect/effect-monster-switcher.cpp
> +    std::string_view spell_name = _("モンスター消滅", "Genocide One");
代入不要です
```c
std::string_view spell_name(_("モンスター消滅", "Genocide One"));
```

2022-02-13 12:38 UTC, Hourier submitted a review, later dismissed
対応お疲れ様でした
内容確認しました
Discordではセーブデータの互換性について議論あるようですが、ひとまずApprove出します
何か見つかったら別チケットにて修正しましょう

2022-02-15 14:49 UTC, merged

2022-02-15 14:49 UTC, Slimebreath6078 commented
ご確認ありがとうございました