Feature/refactor mflag resist
hengband/hengband pull request #2166
Opened 2022-02-12 21:36 UTC by Slimebreath6078

Resolved #1951 
Issueが途中で閉じられてしまうのを回避するために予め定義だけしたものをDraftとして出しておく

2022-02-13 01:30 UTC, Hourier commented
チケットはタスクごとに細分化して作っていくのが良いです
というのは、1つのチケットに複数のPRがあると、1年後に見返した時等に差分が多くなってSAN値が下がるためです

2022-02-15 14:40 UTC, Slimebreath6078 commented
そもそもチケットが違ったので正しい場所に移動しました
その他のフラグについては今からIssue分けいたします

2022-02-15 15:08 UTC, Hourier requested changes
まだrebaseやらコンパイルエラーの解消やら作業があると思われますが、ひとまずフラグ群の部分だけコメントしました
ご確認下さい

2022-02-15 15:08 UTC, Hourier commented on src/monster-race/race-flags-resistance.h
> +    IMMUNE_ACID = 1, /* Immunity acid */
HURT→RESIST→IMMUNE が直感的な順番ですが、酸だけ逆になってます
(セーブデータ等、他に波及しているかもしれないので調査の上修正して下さい)

2022-02-15 15:08 UTC, Hourier commented on src/monster-race/race-flags-resistance.h
> +    RESIST_ALL = 43, /* Resist all */
ALLは一番上にいた方が良さそうです

2022-02-15 15:08 UTC, Hourier commented on src/monster-race/race-flags-resistance.h
> +    MAX, /* Max of Resistances */
以下の4つを追加お願いします (実質予約領域ですが)
* HURT\_ABYSS
* RESIST\_ABYSS
* HURT\_VOID\_MAGIC
* RESIST_VOID\_MAGIC

2022-02-15 15:12 UTC, Hourier commented
monster-loader周りが地獄かもしれないので、新しいloaderを定義してファクトリに乗せてもOKです
作業難易度に応じて詳細お任せします

2022-02-20 07:35 UTC, Hourier approved these changes
簡単ですが動作確認も含めてチェックしました
指摘の反映もなされていて異常な動きも見えなかったのでApproveします
対応お疲れ様でした

2022-02-20 11:54 UTC, Hourier approved these changes
再Approveします

2022-02-20 11:58 UTC, Slimebreath6078 commented
ご確認ありがとうございました

2022-02-20 11:58 UTC, merged