ウィザードモード一部の数値入力にget_value()適用
hengband/hengband pull request #2285
Opened 2022-02-25 14:07 UTC by sikabane-works

ひとまず見て思いついたものを。Issueは閉じず継続し続ける。

2022-02-25 16:28 UTC, habu1010 reviewed
内容は問題ないと思いますが整形がおかしいようです。

2022-02-25 16:28 UTC, habu1010 commented on src/wizard/wizard-game-modifier.cpp
> +    if(!get_value("QuestID", 1, max_q_idx - 1, &tmp_int)) {
ifと(がくっついているので自動整形が行われてないようです。

2022-02-25 22:48 UTC, Hourier reviewed
対応お疲れ様です
文法面で2箇所コメントしました
ご確認下さい

2022-02-25 22:48 UTC, Hourier commented on src/wizard/wizard-game-modifier.cpp
> +    int tmp_int = 0;
処理内容的に変数名は「quest\_num」が良く、また0で初期化する必要はありません

2022-02-25 22:48 UTC, Hourier commented on src/wizard/wizard-special-process.cpp
>      int tmp_int = 0;
処理内容的に変数名は「gametime (またはgame\_time)」が良く、また0で初期化する必要はありません

2022-02-26 03:38 UTC, sikabane-works commented
了解です。コンフリクト含めて一度すべて修正します。

2022-03-25 03:44 UTC, sikabane-works commented
大幅に遅れましたがこの間の修正とのコンフリクト解決して手を加えました。テスト通り次第確認お願いします。

2022-03-26 08:23 UTC, sikabane-works commented
ある程度妥協しましたが、これでまたレビューお願いします。

2022-03-26 13:16 UTC, Hourier reviewed
対応お疲れ様です
内容確認しました
追加で2件コメントしましたのでご確認下さい

2022-03-26 13:16 UTC, Hourier commented on src/wizard/wizard-game-modifier.cpp
> +    tmp_int = atoi(tmp_val);
上で宣言する必要がないのでここでauto宣言しましょう

2022-03-26 13:16 UTC, Hourier commented on src/wizard/wizard-game-modifier.cpp
> -
空行1つ削るのはrebaseで良いと思います

2022-03-26 15:46 UTC, Hourier commented on src/wizard/wizard-game-modifier.cpp
> +    auto tmp_int;
コンパイルエラーが出ているコミットはrebase でdrop した方が良いです
(何かの不具合でbisect中にたまたま踏んづけるとコンパイルエラーの解消から作業しないといけないため)

2022-10-09 05:57 UTC, sikabane-works commented
手直ししたがコンフリクトもかかっているし一度rebaseかける。

2022-10-09 07:04 UTC, sikabane-works commented
半年越しなのでとりあえずチェリーピックで３要素都度指摘部分とリファクタリング変更部分調整しながらforce pushしました。

2022-10-09 07:40 UTC, Hourier requested changes
コンパイルが通ったので確認しました
過去に出したコメント2件が反映されていなかったのと、追加で1点、今までの間にやったリファクタリング結果と齟齬(？)のある箇所が1点あったので、ご確認下さい

2022-10-09 07:40 UTC, Hourier commented on src/wizard/wizard-game-modifier.cpp
> +    auto tmp_int = 0;
「int quest\_num」

2022-10-09 07:40 UTC, Hourier commented on src/wizard/wizard-special-process.cpp
>      int tmp_int = 0;
未対応のままです
「int game\_time;」

2022-10-09 07:40 UTC, Hourier commented on src/wizard/wizard-item-modifier.cpp
> +    auto int_a_idx = static_cast<int>(enum2i(reset_artifact_idx));
intにキャストする必要ありますか？
(左辺をintと明記すれば良いはず)

2022-10-09 11:16 UTC, Hourier approved these changes
対応お疲れ様でした
ひとまず問題なさそうなのでApproveします
get\_value() の引数に参照を入れている課題は別チケットに回しましょう

2022-10-09 11:18 UTC, merged

2022-10-09 11:18 UTC, sikabane-works commented
ありがとうございました。