敵魔法をクラス化した
hengband/hengband pull request #2414
Opened 2022-03-12 14:26 UTC by Slimebreath6078

Resolve #2165 

変更が大きなものなため注意

2022-03-12 14:34 UTC, Hourier approved these changes
対応お疲れ様です
ひとまず文法面で2箇所コメントしました
ご確認下さい

2022-03-12 14:34 UTC, Hourier commented on src/mspell/mspell-util.cpp
> +    : proc([msg_string](auto player_ptr, auto m_idx, auto t_idx, int target_type) {
プロシージャだとかなり意味が汎用的なのでもう少し意味の狭いメソッド名だと嬉しいです

2022-03-12 14:34 UTC, Hourier commented on src/mspell/mspell-ball.cpp
> +    bool result = monspell_message(player_ptr, m_idx, t_idx, msg, target_type);
auto

2022-03-12 14:36 UTC, Hourier requested changes
(間違えてApproveした？ っぽいのでCRに変えときます)

2022-03-12 17:06 UTC, Slimebreath6078 reviewed
ご指摘いただいた個所を修正いたしました
ご確認お願いいたします

2022-03-12 17:06 UTC, Slimebreath6078 commented on src/mspell/mspell-util.cpp
> +    : proc([msg_string](auto player_ptr, auto m_idx, auto t_idx, int target_type) {
`output` に変更いたしました
ついでに`DrsData`の方も`execute`に変更いたしました

2022-03-12 17:06 UTC, Slimebreath6078 commented on src/mspell/mspell-ball.cpp
> +    bool result = monspell_message(player_ptr, m_idx, t_idx, msg, target_type);
auto に変えました

2022-03-13 00:17 UTC, Hourier reviewed
対応お疲れ様です
前回の修正は確認できました
追加で何点かコメントしましたのでご確認下さい

2022-03-13 00:17 UTC, Hourier commented on src/mspell/mspell-breath.cpp
> +    bool known = monster_near_player(floor_ptr, m_idx, t_idx);
auto
(せっかくなので周囲のboolも全部autoにしたいところ)

2022-03-13 00:17 UTC, Hourier commented on src/mspell/mspell-breath.cpp
> +    bool mon_to_player = (target_type == MONSTER_TO_PLAYER);
auto

2022-03-13 00:17 UTC, Hourier commented on src/mspell/mspell-particularity.cpp
> +    return MSpellAttackBase(player_ptr, m_idx, t_idx, MonsterAbilityType::ROCKET, data, target_type,
Baseと銘打たれたクラスのコンストラクタを直接呼ぶのは違和感があります
可能であれば実体となる派生クラスを定義してBaseのコンストラクタはprotectedにしたいです
(コンストラクタを呼べるクラスとその派生クラスが同時にいると設計が壊れがち)

2022-03-13 00:17 UTC, Hourier commented on src/mspell/mspell-attack-util.h
> +    MonsterSpellResult proc(POSITION y, POSITION x);
まだproc() が残っています

2022-03-13 00:20 UTC, Hourier commented on src/mspell/mspell-particularity.cpp
> +    if (target_type == MONSTER_TO_PLAYER) {
MONSTER\_TO\_PLAYER かMONSTER\_TO\_MONSTERの2択なのでelse ifは必要？
(冷静に考えると今までずっとtarget\_typeの扱い自体が怪しかった気もする……boolで良くない？)

2022-03-13 10:37 UTC, Hourier commented on src/mspell/mspell-particularity.cpp
> +    if (target_type == MONSTER_TO_PLAYER) {
考え直した結果、本件は変更範囲が非常に広いことを思い出しました
別チケット対応しましょう

2022-03-14 13:06 UTC, Slimebreath6078 reviewed
ご指摘いただいた個所を修正いたしました
確認お願いいたします

2022-03-14 13:06 UTC, Slimebreath6078 commented on src/mspell/mspell-attack-util.h
> +    MonsterSpellResult proc(POSITION y, POSITION x);
メソッド名を`shoot()`にしました

2022-03-14 13:06 UTC, Slimebreath6078 commented on src/mspell/mspell-breath.cpp
> +    bool known = monster_near_player(floor_ptr, m_idx, t_idx);
全て auto にしました

2022-03-14 13:06 UTC, Slimebreath6078 commented on src/mspell/mspell-breath.cpp
> +    bool mon_to_player = (target_type == MONSTER_TO_PLAYER);
auto にしました

2022-03-14 13:06 UTC, Slimebreath6078 commented on src/mspell/mspell-particularity.cpp
> +    return MSpellAttackBase(player_ptr, m_idx, t_idx, MonsterAbilityType::ROCKET, data, target_type,
それぞれに派生クラスを作るのも行数が多くなってしまうので、糖衣程度のものですが MSpellAttackOther クラスを作成してそれのコンストラクタを呼ぶ形式にしました

2022-03-16 10:33 UTC, Hourier commented on src/mspell/mspell-attack-util.h
> +    virtual ~MSpellAttackBase() = default;
デストラクタはpublicにして下さい
(アップキャストした時にデストラクタを呼べないため)

2022-03-16 11:52 UTC, habu1010 reviewed
量が多いのですべては見切れていませんが、目についたものをコメントしました。
また、MSVCが
```
warning C4868: コンパイラでは、中かっこで囲まれた初期化子リストの評価順序を左から右方向に設定できない場合があります
```
という警告を大量に出力しています。

2022-03-16 11:52 UTC, habu1010 commented on src/mspell/mspell-util.h
> +    const MessageData msg;
move ができなくなるので、クラス内クラスを含めすべてのメンバ変数から const を外したほうがいいです。
MSVCの移動代入コンストラクタの暗黙削除についての警告の抑止にもなります。

2022-03-16 11:52 UTC, habu1010 commented on src/mspell/mspell-util.h
> +        return map.at(key);
一度同じキーを無駄に2度検索しています。
```c++
if (auto it = map.find(key); it != map.end()) {
    return it->second;
}
```
とするべきです。

2022-03-16 11:52 UTC, habu1010 commented on src/mspell/mspell-attack-util.cpp
> +    , fire(fire)
`data(class MSpellData)`、`fire(std::function<>)` はコピーのコストを抑えるため、 std::move したほうがいいです。（他のコンストラクタでの初期化についても同様）

2022-03-16 12:05 UTC, habu1010 reviewed
もう1点追記しました。

2022-03-16 12:05 UTC, habu1010 commented on src/mspell/mspell-bolt.cpp
> +          })
親クラスのコンストラクタ呼び出しの時点では this は初期化が完了していないので、それにアクセスするのは未定義動作です。
this ではなくコンストラクタの引数をコピーキャプチャして使用してください。
MSpellBall も同様です。

2022-03-19 06:17 UTC, Slimebreath6078 reviewed
ご指摘いただいた個所を修正いたしました
また、発生していた警告も一通り潰しました
ご確認お願いいたします

2022-03-19 06:17 UTC, Slimebreath6078 commented on src/mspell/mspell-attack-util.h
> +    virtual ~MSpellAttackBase() = default;
デストラクタを public にしました

2022-03-19 06:17 UTC, Slimebreath6078 commented on src/mspell/mspell-util.h
> +    const MessageData msg;
メンバ変数の const を外しました

2022-03-19 06:17 UTC, Slimebreath6078 commented on src/mspell/mspell-util.h
> +        return map.at(key);
提示されてる処理に書き換えました

2022-03-19 06:17 UTC, Slimebreath6078 commented on src/mspell/mspell-attack-util.cpp
> +    , fire(fire)
ムーブするように初期化子を変更しました

2022-03-19 06:17 UTC, Slimebreath6078 commented on src/mspell/mspell-bolt.cpp
> +          })
キャプチャを \[=\] にしました

2022-03-19 15:51 UTC, habu1010 reviewed
私の指摘事項に関して修正を確認しました。
const を外したのに関連して1点だけ追記しています。

2022-03-19 15:51 UTC, habu1010 commented on src/mspell/mspell-util.h
> +    virtual ~MSpellData() = default;
MSpellData クラスに関しては、コピーコンストラクト/コピー代入/ムーブコンストラクト/ムーブ代入すべてできてよさそうなので、すべての特殊メンバ関数を明示的に = default; として示しておいたほうがよさそうです。
特に、現状のコードだとC++の規格により、ムーブコンストラクト/ムーブ代入は暗黙に生成されずムーブできる場合でもコピーとなります。
ラムダ式オブジェクトを所持しているためコピーコストが高めなので、ムーブもできたほうがベターかと思います。（現在は用途が限定的なのでムーブできなくてもそれほど影響は無いですが）

2022-03-19 17:04 UTC, Slimebreath6078 commented on src/mspell/mspell-util.h
> +    virtual ~MSpellData() = default;
コピー代入、ムーブコンストラクタ、ムーブ代入の明示定義を追加いたしました
ご確認お願いいたします

2022-03-19 22:54 UTC, habu1010 commented on src/mspell/mspell-util.h
> +    virtual ~MSpellData() = default;
修正確認しました。
デバッグ出力で確かめたところ、実際にムーブコンストラクタが無事使われているようです。

2022-03-19 22:57 UTC, habu1010 commented
私からは大体以上です。
一応もう1点だけ書いておくと、MspellBreath というクラスが定義だけされていて実際には使用されていないようです。（spell_RF4_BREATH を置き換えるつもりで作ったけど途中でやめた？）

2022-03-20 02:42 UTC, Slimebreath6078 commented
MSpellBreath を消して、そのついでに不要そうなデストラクタの明示定義を消しました

2022-03-20 10:49 UTC, Slimebreath6078 commented
警告を一通り潰しました

2022-03-23 09:09 UTC, Hourier reviewed
対応お疲れ様です
内容確認し、何箇所かコメントしました
ご確認下さい

また、mspell-util.h に定義されているクラス/構造体が入れ子含めて6個あるので、utilと呼ぶには少し肥大化しているかもしれません
設計上問題ない範囲でまとまっているとは思いますが、もしより良い分離方法があれば分離すると良いかと思います
(元々utilと名付けたのはC言語時代の手続き的設計上の理由：モンスターの呪文に関して広範囲から呼ばれている関数をまとめただけに過ぎないため)

2022-03-23 09:09 UTC, Hourier commented on src/mspell/mspell-breath.cpp
> +    int dam = 0;
auto

2022-03-23 09:09 UTC, Hourier commented on src/mspell/mspell-util.h
> +    class MessageData {
外から呼ばれていて入れ子になっている必要性が薄いと思われます
入れ子ではなく普通に定義しても良さそうです
DrsDataも同様です

2022-03-24 16:12 UTC, Slimebreath6078 reviewed
ご指摘いただいた個所を修正いたしました

mspell-util.cpp/h に追加していたクラスは mspell-data.cpp/h を作成し、その中に移動いたしました
また追加で mspell-attack-util.cpp/h に追加していたクラスは mspell-attack/mspell-abstract.cpp/h に移し、その他攻撃魔法も同ディレクトリに移動いたしました

お手数をおかけしますが、ご確認お願いいたします

2022-03-24 16:12 UTC, Slimebreath6078 commented on src/mspell/mspell-attack-util.cpp
> +MSpellAttackAbstract::MSpellAttackAbstract(PlayerType *player_ptr, MONSTER_IDX m_idx, MonsterAbilityType ability, MSpellData data, int target_type, std::function<ProjectResult(POSITION, POSITION, int
AbstractMSpellAttack に改名しました

2022-03-24 16:12 UTC, Slimebreath6078 commented on src/mspell/mspell-breath.cpp
> +    int dam = 0;
auto に変えました

2022-03-24 16:12 UTC, Slimebreath6078 commented on src/mspell/mspell-util.h
> +    class MessageData {
双方 MSpell\*\*\* で入れ子から出しました

2022-03-27 12:24 UTC, Hourier commented on Hengband/Hengband/Hengband.vcxproj
> +    <ClCompile Include="..\..\src\mspell\mspell-attack\mspell-abstract.cpp" />
クラス名との対比を考えると、abstract-mspell の方が良さそうです (ヘッダも同様、自動整形に注意)

2022-03-27 14:04 UTC, Slimebreath6078 reviewed
修正いたしました
ご確認お願いいたします

2022-03-30 10:13 UTC, Hourier reviewed
対応お疲れ様です
文法面で2箇所追加コメントを付けました
ご確認下さい

2022-03-30 10:13 UTC, Hourier commented on src/mspell/mspell-attack/mspell-ball.cpp
> +    bool known = monster_near_player(player_ptr->current_floor_ptr, m_idx, t_idx);
auto
本関数内も同様

2022-03-30 10:13 UTC, Hourier commented on src/mspell/mspell-attack/mspell-bolt.cpp
> +    bool notice = monspell_message(player_ptr, m_idx, t_idx, msg, target_type);
auto

2022-03-30 10:58 UTC, Hourier approved these changes
長期間の対応お疲れ様でした
追加の指摘はありません
Approveします
ここから先は何かあっても別チケットで対応していきましょう

2022-03-30 11:35 UTC, Slimebreath6078 commented
ご確認ありがとうございました

2022-03-30 11:35 UTC, merged