store_table近辺リファクタリング
hengband/hengband pull request #2715
Opened 2022-10-10 16:23 UTC by sikabane-works

まだ途中。

2022-10-23 16:09 UTC, sikabane-works commented
レビューお願いします。

2022-10-24 11:24 UTC, Hourier requested changes
対応お疲れ様です
いくつかコメントしました
1つは今後バグ調査の際に困る可能性があるのでCRとして出しておきます
ご確認下さい

2022-10-24 11:24 UTC, Hourier commented on src/store/articles-on-sale.h
> +#include <map>
これは3つ目のコミットにまとめて下さい
(bisectした時にこのコミットを踏んづけるとコンパイルが通らなくなるため)

2022-10-24 11:24 UTC, Hourier commented on src/market/building-initializer.cpp
>                  if (tv == ItemKindType::NONE) {
このif文は通らなくなったので不要です

2022-10-24 11:24 UTC, Hourier commented on src/market/building-initializer.cpp
> +            const auto store_r = store_regular_table[sst];
↓と書き直した方が良いです (参照を取らないとコピーになる、atでアクセスしないと予期しないvectorが生成される)
```cpp
const auto &store_r = store_regular_table.at(sst);
```

2022-10-25 09:39 UTC, habu1010 reviewed
動作に直接影響があるところではないですが、ボーイスカウト・ルールに則り修正したほうがよさそうなところをコメントしました。

2022-10-25 09:39 UTC, habu1010 commented on src/store/articles-on-sale.cpp
> +std::map<StoreSaleType, std::vector<store_stock_item_type>> store_regular_table = {
読み取り専用データなので、この際 const をつけるようにしたほうがよいでしょう。
const をつけると、自動的にキーアクセスに operator[] ではなく at() を使うことにもなります。

また、変数名がやや曖昧（店に売り出される商品のデータという意味が汲み取れない）に思えるので、 store_regular_sale_table にしたほうがよさそうです。

2022-10-25 09:39 UTC, habu1010 commented on src/store/articles-on-sale.cpp
> +std::map<StoreSaleType, std::vector<store_stock_item_type>> store_table = {
store_regular_table と同様のことがいえます。

2022-10-25 11:40 UTC, sikabane-works commented
ありがとうございます。とりあえずrebaseで全部巻き直すくらいで片づけます。

2022-10-30 00:23 UTC, sikabane-works commented on src/store/articles-on-sale.cpp
> +std::map<StoreSaleType, std::vector<store_stock_item_type>> store_table = {
const付加とstore_sale_tableに改名します。

2022-10-30 00:50 UTC, sikabane-works commented on src/market/building-initializer.cpp
>                  if (tv == ItemKindType::NONE) {
指示通り削除します。

2022-10-30 01:11 UTC, sikabane-works commented on src/store/articles-on-sale.h
> +#include <map>
mapへの変更は1つ目のstore_tableの改変から用いるのでそこから#include<map>を加えました。

2022-10-30 01:17 UTC, Hourier commented on src/market/building-initializer.cpp
>                  if (k_idx == 0) {
tval とsval の組み合わせが正しいかはコンパイル時にテーブル側で決まることなので、このif文は冗長につき不要です

2022-10-30 01:57 UTC, sikabane-works commented on src/store/articles-on-sale.cpp
> +std::map<StoreSaleType, std::vector<store_stock_item_type>> store_regular_table = {
const向けにatメソッドでの参照、改名共に採用しました。

2022-10-30 01:58 UTC, sikabane-works commented on src/store/articles-on-sale.h
> +#include <map>
今後、各コミットの際に都度プッシュして通るかテストする慣習でいきます。

2022-10-30 02:29 UTC, sikabane-works commented
一通り手直しできたと思われますので再度レビューお願いします。

2022-10-30 07:53 UTC, habu1010 commented on src/market/building-initializer.cpp
> +            const auto store_r = store_regular_sale_table.at(sst);
ここを参照で受けるべきという指摘が反映されていないようです。（参照で受けないとvectorが保持している配列を不要にコピーしてしまう）
そもそも変数の使用箇所が一箇所のみであり、説明的変数名でもないので一旦変数に受けずそのままfor文に入れてしまって良いかもしれません。

2022-10-30 07:53 UTC, habu1010 commented on src/market/building-initializer.cpp
> +            const auto store = store_sale_table.at(sst);
同上

2022-10-30 11:57 UTC, sikabane-works commented on src/market/building-initializer.cpp
> +            const auto store_r = store_regular_sale_table.at(sst);
for文に直接入れました。

2022-10-30 11:57 UTC, sikabane-works commented on src/market/building-initializer.cpp
> +            const auto store = store_sale_table.at(sst);
修正も同じく

2022-10-30 12:07 UTC, Hourier reviewed
2点追加でコメントしました
単に「&」を付けるだけですが間に合わないようでしたら次のαで良いと思います

2022-10-30 12:07 UTC, Hourier commented on src/market/building-initializer.cpp
> +            for (const auto kind : store_regular_sale_table.at(sst)) {
悩ましいですが、vectorから取り出しているのはプリミティブではなく構造体なので、参照で受けた方が良いと思います
(今はプリミティブ2つしかないですが、この後色々生やす予定があるので)

2022-10-30 12:07 UTC, Hourier commented on src/market/building-initializer.cpp
> +            for (const auto kind : store_sale_table.at(sst)) {
同上

2022-10-30 12:34 UTC, Hourier approved these changes
対応お疲れ様でした
もう問題ないのでApproveします

2022-10-30 12:34 UTC, merged