show_file() の引数をchar* からstring_view に変えた
hengband/hengband pull request #3380
Opened 2023-06-08 13:59 UTC by Hourier

掲題の通りです
静的解析との兼ね合いで先にやっておいた方が良さそうだと判断し実施しました
更に、what 引数はnullptr になっている箇所が相当数見受けられたのでオプション引数にしました
ご確認下さい

2023-06-08 22:21 UTC, habu1010 requested changes

2023-06-09 10:08 UTC, Hourier commented on src/core/show-file.cpp
> +        stripped_name.append(name, tag - name.data());
呼び出し元を探った結果、「hoge.txt#fuga」という形式だったので、str\_split() を使って分割することにしました

2023-06-09 10:09 UTC, Hourier commented
確認ありがとうございます
コメントを修正した他、次のリファクタリングに繋げやすいように各所調整しました
追加コミット分と合わせてチェック願います

2023-06-09 10:59 UTC, habu1010 commented on src/core/show-file.cpp
> +        caption << what;
`caption = hogehoge;` となっていたところを `caption << hogehoge;` に変えてしまっては、どんどん追記されていってしまうのではないでしょうか。

2023-06-09 10:59 UTC, Hourier commented on src/core/show-file.cpp
> +        caption << what;
clearします！

2023-06-09 11:13 UTC, Hourier commented on src/core/show-file.cpp
> +        caption << what;
それぞれclear() するようにしてforce push しました

2023-06-09 11:20 UTC, habu1010 reviewed
ヘルプでタグ付きの項目を選択すると、`'#タグ'をオープンできません` というメッセージが出て開けません。

2023-06-09 11:40 UTC, habu1010 commented on src/core/show-file.cpp
> +        prt(format(title, H_VER_MAJOR, H_VER_MINOR, H_VER_PATCH, caption_str.data(), line, size), 0, 0);
今回の修正と直接関係ないのですが、ここからの一連の最上行の表示は、v2.2.1だと以下のようになっています。

```c++
                if (show_version)
                {
                        prt(format(_("[変愚蛮怒 %d.%d.%d, %s, %d/%d]", "[Hengband %d.%d.%d, %s, Line %d/%d]"),
                           FAKE_VER_MAJOR-10, FAKE_VER_MINOR, FAKE_VER_PATCH,
                           caption, line, size), 0, 0);
                }
                else
                {
                        prt(format(_("[%s, %d/%d]", "[%s, Line %d/%d]"),
                                caption, line, size), 0, 0);
                }
```

どこかでcaptionと行番号を表示しなくなったようですが、どういう経緯があったかわかるでしょうか？
いずれにしても、今の仕様であれば、この部分はすぐに上書きされてしまうので不要ということになりそうです。

2023-06-09 12:00 UTC, Hourier commented on src/core/show-file.cpp
> +        prt(format(title, H_VER_MAJOR, H_VER_MINOR, H_VER_PATCH, caption_str.data(), line, size), 0, 0);
Discord の議論に従い、1個修正コミットを重ねました
ご確認下さい

2023-06-09 12:10 UTC, habu1010 approved these changes
最上行の表記が以前の形式に戻っているのも確認できました。
Approveします。

2023-06-09 12:13 UTC, merged

2023-06-09 12:13 UTC, Hourier commented
確認ありがとうございました！