get_string() からchar* の引数を削除し、戻り値をoptional<string> に変えた
hengband/hengband pull request #3420
Opened 2023-06-13 09:04 UTC by Hourier

掲題の通りです
デバッグコマンドを中心にいくつか検証しましたが特に問題は検出されませんでした
ご確認下さい

2023-06-13 13:28 UTC, habu1010 requested changes
目を通す以前に根本的な問題がありますので、その点についてコメントしました。

2023-06-13 13:28 UTC, habu1010 commented on src/core/asking-player.cpp
> +        return std::nullopt;
まず前提として、空文字列の時にnulloptを返すのはまずいのではないでしょうか。
get_stringの戻り値が空文字列だった時に特別な処理をする、というパターンが多くありますが、それができなくなります。

2023-06-13 13:39 UTC, Hourier commented on src/core/asking-player.cpp
> +        return std::nullopt;
確かにその通りですね
修正してforce push しました

2023-06-13 15:16 UTC, habu1010 requested changes
多数の問題点が見つかりましたのでコメントしました。
（チェックしきれた自信無いです。複数人でチェックしたほうがよさそうです。）

2023-06-13 15:16 UTC, habu1010 commented on src/wizard/wizard-item-modifier.cpp
> +    o_ptr->pval = clamp_cast<int16_t>(std::stoi(pval));
stoi(略)

2023-06-13 15:16 UTC, habu1010 commented on src/wizard/wizard-item-modifier.cpp
> +    o_ptr->to_a = clamp_cast<int16_t>(std::stoi(ac));
stoi(略)

2023-06-13 15:16 UTC, habu1010 commented on src/wizard/wizard-item-modifier.cpp
> +    o_ptr->to_h = clamp_cast<int16_t>(std::stoi(hit));
stoi(略)

2023-06-13 15:16 UTC, habu1010 commented on src/wizard/wizard-item-modifier.cpp
> +        wish = str_ltrim(wish.substr(0, _(10, 7)));
substrで切り出す範囲あってますか？

2023-06-13 15:16 UTC, habu1010 commented on src/wizard/wizard-item-modifier.cpp
> +            wish = str_ltrim(wish.substr(0, fixed_string.length()));
同上

2023-06-13 15:16 UTC, habu1010 commented on src/wizard/wizard-item-modifier.cpp
> +        wish = str_ltrim(wish.substr(0, 2));
同上

2023-06-13 15:16 UTC, habu1010 commented on src/wizard/wizard-item-modifier.cpp
> +        wish = str_ltrim(wish.substr(0, _(2, 4)));
同上

2023-06-13 15:16 UTC, habu1010 commented on src/wizard/wizard-item-modifier.cpp
> +        wish = str_ltrim(wish.substr(0, _(6, 9)));
同上

2023-06-13 15:16 UTC, habu1010 commented on src/wizard/wizard-special-process.cpp
> +    auto weapon_exp = std::clamp(static_cast<short>(std::stoi(proficiency.value())),
stoi(略)

2023-06-13 15:16 UTC, habu1010 commented on src/wizard/wizard-special-process.cpp
> +    const auto new_exp = std::max(std::stoi(new_exp_opt.value()), 0);
stoi(略)

2023-06-13 15:16 UTC, habu1010 commented on src/wizard/wizard-special-process.cpp
> +        auto tmp_command_arg = static_cast<short>(std::stoi(new_level.value()));
stoi(略)

2023-06-14 10:05 UTC, Hourier commented
「そもそも数値しか受け入れていない箇所でget\_string() を呼ぶのはおかしい、get\_value() があるのだからそれを使うべき」という意見がDiscord で出ました
その方が明らかに合理的なのでそちらにまず寄せる方針とし、このブランチは一旦クローズとします

2023-06-14 10:05 UTC, closed without merging