get_value() の引数からchar* を消し、戻り値をoptional<string> に変えた
hengband/hengband pull request #3435
Opened 2023-06-17 08:36 UTC by Hourier

掲題の通りです
見た感じ動いているように見えますが、特に%から飛ぶ各種変更コマンドはあまり使ったことがないので、細かい正しさまではハッキリしません
お手数ですが使用経験のある方にチェック頂きたいです

2023-06-17 11:12 UTC, Hourier commented
異常な日記が生成されたので一旦ドラフトにします (developはOKなのでこのブランチの問題)

2023-06-17 12:16 UTC, Hourier commented
修正できましたのでReady for review に戻します

2023-06-17 14:05 UTC, habu1010 reviewed
いくつかコメントしました。ご確認ください。

また、get_valueのシグネチャに関する提案なのですが、戻り値に対して非常に多くキャストが使われているのがきになるので、以下のようにするのはどうでしょうか。

```c++
/// asking-player.h

// 今のget_valueをget_value_intにする
std::optional<int> get_value_int(std::string_view prompt, int min, int max, int initial_value);

// get_valueを関数テンプレートにし、initial_value で型を推論する
template <typename T>
std::optional<T> get_value(std::string_view prompt, int min, int max, T initial_value) {
    return static_cast<T>(get_value_int(prompt, min, max, static_cast<int>(initial_value)));
}
```

こうすることで、呼び出し側はキャストによる煩雑さをなくせると思います。

```c++
// 呼び出し側
short initial_value = 42;
auto value1 = get_value(..., initial_value); // value1 はshortになる

Enum initial_ev = Enum::NONE;
auto value2 = get_value(..., initial_ev); // enumにも対応

auto value3 = get_value<short>(...); // 初期値を省略した場合も型を指定することができる
```

2023-06-17 14:36 UTC, Hourier commented on src/core/asking-player.cpp
> +            msg_print(_("数値を入力して下さい。", "Please input numeric value."));
設計上、その時には初期値と入力値が別になるので必ず初期値に戻るようになります
後ほど実施します

2023-06-17 14:43 UTC, Hourier commented on src/wizard/wizard-item-modifier.cpp
> +        artifacts.get_artifact(reset_artifact_idx).is_generated = aware;
get\_value() の導入によってcommand\_arg を使わなくても番号の指定ができるようになったので、外からの指定はできなくした方が良さそうですね
これは別途作業が落ち着いたら開発者間で相談したいです
(回数と番号を同列に扱っている今のデバッグコマンド自体がバギー)

2023-06-18 03:10 UTC, Hourier commented
コメントに対応しました
まだcmd-visuals.cpp がナローキャスト警告を出しているので一旦ドラフトにしておきます
火曜日以降に対応します

2023-06-18 08:21 UTC, habu1010 commented on src/util/string-processor.cpp
> +        if (part.starts_with(needle.substr(0, l2))) {
`needle.substr(0, l2)` は `needle` そのものじゃないでしょうか。

2023-06-18 08:21 UTC, habu1010 commented on src/wizard/wizard-game-modifier.cpp
> +    const auto quest_num = input_value<short>("QuestID", 0, quest_max - 1);
テンプレート型は推論されるので不要です。
もしくはこの場合は

```c++
const auto quest_num = input_value("QuestID", 0, i2enum<QuestId>(quest_max - 1));
```

とすると quest_num は `std::optional<QuestId>` になるので、後のキャストが不要になります。
他のinput_value使用箇所も同様のことが言えます。

2023-06-18 08:21 UTC, habu1010 commented on src/wizard/wizard-special-process.cpp
> +    const auto new_race = input_value("RaceID", 0, MAX_RACES - 1, original_race);
一旦original_raceに入れずに、そのまま
```c++
const auto new_race = input_value("RaceID", 0, MAX_RACES - 1, player_ptr->prace);
```
とすれば良いと思います。
そうすることで new_race が `std::optional<PlayerRaceType>` になるので後の i2enum も不要になっていいことずくめです。

この後にある wiz_reset_class() の PlayerClassType でも同じことが言えます。

2023-06-18 08:21 UTC, habu1010 commented on src/wizard/wizard-special-process.cpp
> +    player_ptr->realm2 = static_cast<int16_t>(new_realm2.value());
shortをint16_tにキャストしてるので不要なのではないでしょうか。

2023-06-18 08:21 UTC, habu1010 commented on src/wizard/wizard-spells.cpp
>      auto idx = enum2i(effect_idx);
enum2iで整数にせず、 idx をそのまま AttributeType で扱ったほうが後の i2enum が要らなくなりそうです。

2023-06-20 11:18 UTC, Hourier commented
頂いたコメントを修正してforce push しました (漏れがあったらすみません)
ご確認下さい

2023-06-20 13:55 UTC, habu1010 commented
画面表示の設定コマンド '%' の挙動がおかしいようです。

確認した現象は、

- 'n'/'N' によるモンスター番号の増減の動作がおかしい（'a'/'A' および 'c'/'C' によるシンボル・色の増減は正しくうごいている模様）
- ’^N'、'^A'、'^C'による数値の入力プロンプトがおかしい（下はモンスター番号入力 '^N' の例）

<img width="326" alt="image" src="https://github.com/hengband/hengband/assets/1501750/ef673bff-4e33-40ec-84d9-f4aac11e9470">

2023-06-20 14:54 UTC, habu1010 requested changes
追加でコメントしました。
上で言及した動作不良の修正とあわせてお願いします。
コードに関するコメントは以上になると思います。

2023-06-20 14:54 UTC, habu1010 commented on src/core/asking-player.h
> +template <typename T>
誤って整数型/enum(class)以外で使用しないように、以下のコンセプトを指定しておいてください。

```c++
    requires std::is_integral_v<T> || std::is_enum_v<T>
```

2023-06-20 14:54 UTC, habu1010 commented on src/autopick/autopick-matcher.cpp
> +        if (item_name.find(entry.name) == std::string_view::npos) {
実用上1文字のアイテム名を指定して自動拾いエントリを作ることは無いと思いますが、プログラムの正しさとしてはダメ文字対策としてangband_strstrにしておいたほうがよさそうです。

2023-06-23 15:13 UTC, Hourier commented
コメント頂いた問題の修正とコード変更が完了しました
ご確認下さい

2023-06-23 15:35 UTC, habu1010 commented
シンボルエディタの動きがおかしいです。

- (4) モンスターの 色/文字 を変更する（数値操作）
  - '^N' の数値入力時に候補が 0 からではなく 1 からになる 
- (5) アイテムの色/文字 を変更する（数値操作）
  - 'n' 'N' を押しても値が変わらない
  - '^N' で入力しても0固定のまま反映されない
- (6) 地形の色/文字 を変更する（数値操作）
  - 'n' 'N' を押すとハングする
  - '^N' を押すと数値入力から抜けられなくなる

またメッセージログで検索・強調どちらでもAddressSanitizerのチェックによりクラッシュが発生します。

クラッシュログ：
```
=================================================================
==342038==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6030000738be at pc 0x7ffff7609aa7 bp 0x7fffffffcd60 sp 0x7fffffffc508
READ of size 1 at 0x6030000738be thread T0
    #0 0x7ffff7609aa6 in __interceptor_strlen ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:389
    #1 0x55555bd41d6b in std::char_traits<char>::length(char const*) /usr/include/c++/11/bits/char_traits.h:399
    #2 0x55555bd42b14 in std::basic_string_view<char, std::char_traits<char> >::basic_string_view(char const*) /usr/include/c++/11/string_view:132
    #3 0x55555d96cdb5 in angband_strstr(char const*, std::basic_string_view<char, std::char_traits<char> >) util/string-processor.cpp:483
    #4 0x55555c0d1610 in do_cmd_messages(int) cmd-visual/cmd-draw.cpp:212
    #5 0x55555c93c6c5 in process_command(PlayerType*) io/input-key-processor.cpp:623
    #6 0x55555c1342fd in process_player(PlayerType*) core/player-processor.cpp:325
    #7 0x55555c168291 in process_dungeon(PlayerType*, bool) dungeon/dungeon-processor.cpp:229
    #8 0x55555c121a94 in process_game_turn core/game-play.cpp:366
    #9 0x55555c122892 in play_game(PlayerType*, bool, bool) core/game-play.cpp:449
    #10 0x55555cb9af61 in main /home/habu/hengband/build/main.cpp:438
    #11 0x7ffff63b8d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #12 0x7ffff63b8e3f in __libc_start_main_impl ../csu/libc-start.c:392
    #13 0x55555bd3fcf4 in _start (/home/habu/hengband/src/hengband+0x67ebcf4)

0x6030000738be is located 0 bytes to the right of 30-byte region [0x6030000738a0,0x6030000738be)
allocated by thread T0 here:
    #0 0x7ffff76821c7 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x55555bd71950 in __gnu_cxx::new_allocator<char>::allocate(unsigned long, void const*) /usr/include/c++/11/ext/new_allocator.h:127
    #2 0x55555bd6a199 in std::allocator<char>::allocate(unsigned long) /usr/include/c++/11/bits/allocator.h:185
    #3 0x55555bd6a199 in std::allocator_traits<std::allocator<char> >::allocate(std::allocator<char>&, unsigned long) /usr/include/c++/11/bits/alloc_traits.h:464
    #4 0x55555bd6becf in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long) /usr/include/c++/11/bits/basic_string.tcc:153
    #5 0x55555bdb9276 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) /usr/include/c++/11/bits/basic_string.tcc:219
    #6 0x55555bdb8e59 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct_aux<char*>(char*, char*, std::__false_type) /usr/include/c++/11/bits/basic_string.h:255
    #7 0x55555bdb8b96 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*) /usr/include/c++/11/bits/basic_string.h:274
    #8 0x55555bdb875c in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/include/c++/11/bits/basic_string.h:459
    #9 0x55555d9c69c0 in message_str[abi:cxx11](int) view/display-messages.cpp:89
    #10 0x55555c0d11f4 in do_cmd_messages(int) cmd-visual/cmd-draw.cpp:203
    #11 0x55555c93c6c5 in process_command(PlayerType*) io/input-key-processor.cpp:623
    #12 0x55555c1342fd in process_player(PlayerType*) core/player-processor.cpp:325
    #13 0x55555c168291 in process_dungeon(PlayerType*, bool) dungeon/dungeon-processor.cpp:229
    #14 0x55555c121a94 in process_game_turn core/game-play.cpp:366
    #15 0x55555c122892 in play_game(PlayerType*, bool, bool) core/game-play.cpp:449
    #16 0x55555cb9af61 in main /home/habu/hengband/build/main.cpp:438
    #17 0x7ffff63b8d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: heap-buffer-overflow ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:389 in __interceptor_strlen
Shadow bytes around the buggy address:
  0x0c06800066c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c06800066d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c06800066e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c06800066f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0680006700: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c0680006710: fa fa fa fa 00 00 00[06]fa fa fd fd fd fd fa fa
  0x0c0680006720: fd fd fd fa fa fa fd fd fd fd fa fa fd fd fd fd
  0x0c0680006730: fa fa fd fd fd fa fa fa fd fd fd fa fa fa fd fd
  0x0c0680006740: fd fd fa fa fd fd fd fd fa fa fd fd fd fd fa fa
  0x0c0680006750: fd fd fd fd fa fa fd fd fd fd fa fa fd fd fd fd
  0x0c0680006760: fa fa fd fd fd fd fa fa fd fd fd fd fa fa fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==342038==ABORTING

```

2023-06-23 15:56 UTC, habu1010 commented on src/cmd-visual/cmd-draw.cpp
>              }
このAddressSanitizerによるチェックでのクラッシュはこのループで発生しているようです。

```c++
                str = const_cast<char *>(std::string_view(str).substr(len).data());
```

この処理はfindを使っていた時のもので、angband_strstrに戻したら必要無いのではないでしょうか？これが原因で文字列の範囲外アクセスしているように見えます。

2023-06-24 01:06 UTC, Hourier commented
頂いた事象を解決しました
お手数おかけしますがご確認下さい

2023-06-24 01:44 UTC, habu1010 commented
まだシンボルエディタがおかしいです。

- (4) モンスターの 色/文字 を変更する（数値操作）
  - a/A/^A および c/C/^C コマンドの範囲がおかしい（developブランチでは0-255）
- (5) アイテムの色/文字 を変更する（数値操作）
  - ^N の数値入力からESCで抜けられない
- (6) 地形の色/文字 を変更する（数値操作）
  - ^N の数値入力からESCで抜けられない

また、メッセージログの'='(強調)コマンドの挙動がおかしいです。すぐに反映されず、2回コマンドを実行すると1回前のコマンドで指定した文字列が強調表示されている感じです。

2023-06-24 02:41 UTC, Hourier commented
上記4点修正してforce pushしました
ご確認下さい

2023-06-24 03:01 UTC, habu1010 commented
上記4点の修正を確認しました。
確認した範囲では残り1つだけ問題点があり、(6)の地形エディタでゲームの都合上設定できないID（例えば ID 2 の隠れたトラップ）の数値を入力すると確定せずにもう1度入力を促されます（ここまではdevelopと同じ）が、そこでESCを押すと入力した数値が反映されてしまうようです（developでは元の数値に戻る）。

2023-06-24 03:16 UTC, Hourier commented
修正しました
ベースアイテムIDの欠番 (ex. 460)を指定→再入力プロンプト表示 → Escキャンセル で同じ問題が起こるのでそれも修正しました
ご確認下さい

2023-06-24 03:59 UTC, habu1010 approved these changes
修正確認しました。とりあえず確認した範囲では以前の動作を保つようになったようです。Approveします。

ただ、本 PR と関係なくメッセージログの検索の挙動が、画面内に該当の文字列が無い時に画面外の文字へスクロールしてくれないという直感的じゃない動作をしています（developでも同じ）。

昔からこうだったのか、確認したほうがよさそうです。

それから、message_str()の戻り値がconst char* から std::string になりましたが、メッセージ検索時に最大81920 × 1行の文字 の文字数のコピーが発生してしまいます。
折角過去のメッセージはshared_ptrで保持しているので、shared_ptrを返すようにしたほうがよいと思います。これは私が別PRでやろうと思います。

2023-06-24 04:06 UTC, merged

2023-06-24 04:07 UTC, Hourier commented
確認ありがとうございました！
shared\_ptr の件はよろしくお願いします
自動スクロールの件は、ひとまずチケットだけ立てておきます
(askfor 等のシグネチャ周りが引き起こしているコードが汚い状態は早めに浄化したい)