静的警告の解消 その7
hengband/hengband pull request #3457
Opened 2023-06-24 09:57 UTC by Hourier

※ 厳密には静的警告はget\_string() やaskfor() 周りの文字列操作部分で起きているので、その準備

概ね以下の3点を実施しました (3つ目がそこそこ重い)
ご確認下さい
- angband\_strstr() のラッピング
- 構造体の未初期化警告対応
- get\_string() のシグネチャ変更に備えたinput\_value() への呼び出し変更

2023-06-24 10:23 UTC, habu1010 commented
入力の範囲が重複しています。
すみませんがまず変更した場所は全部チェックお願いします。それから見ます。

<img width="279" alt="image" src="https://github.com/hengband/hengband/assets/1501750/a6300b2d-5795-4550-bb97-c60057dfd18f">

2023-06-24 14:12 UTC, Hourier commented
修正完了しました
ご確認下さい

2023-06-24 18:19 UTC, habu1010 requested changes
数値入力の処理が非常にスッキリしたと思います。
一通りチェックしてコメントしました。

2023-06-24 18:41 UTC, Hourier commented on src/util/string-processor.cpp
> +    return angband_strstr(src.data(), find) != nullptr;
(他との整合性もありますが) 引数を「const string &」で受けるのはどうでしょうか？
ひとまず現状ではstring\_view を直接渡している箇所はありませんでした

2023-06-24 18:57 UTC, Hourier commented on src/floor/pattern-walk.cpp
> +    command_arg = std::clamp<short>(command_arg, static_cast<short>(min_level), static_cast<short>(max_level));
ロジックを見返してみましたがcommand\_arg に必ず代入されてからこの行に入りますね
削除します

2023-06-24 18:59 UTC, habu1010 commented on src/util/string-processor.cpp
> +    return angband_strstr(src.data(), find) != nullptr;
第1引数の型を const std::string& にすると、str_findの第1引数にconst char* もしくは std::string_view を渡すと（本来 const char* や std::string_view が指している文字列上で検索できるはずにもかかわらず）不要なstringオブジェクトが生成されるというデメリットが発生します。
まあ、クリティカルパスで使用するのでなければそのくらいのオーバーヘッドは気にしないということでもよいかと思います。std::string_view::subspan などで範囲を絞ったオブジェクトを渡して事故るよりははるかにマシでしょう。

2023-06-24 19:02 UTC, Hourier commented on src/market/play-gamble.cpp
> +                break;
ここはwhile (true) で「ベットしたら必ず番号を指定させる」としました
(どの道掛け金は戻ってこないので、賭けずに抜けられる仕組みを用意する必要はないという判断)

2023-06-24 19:03 UTC, Hourier commented on src/util/string-processor.cpp
> +    return angband_strstr(src.data(), find) != nullptr;
承知しました
ではこの方針で進めます

2023-06-24 19:07 UTC, habu1010 reviewed
1件追加で不具合：
デバッグコマンドのフロアジャンプ (^a j) で地上（0階）が指定できなくなっています。
元々、 10階から20階までのダンジョンの場合、「(0, 10-20)」のように表示されていたので、input_integer との整合性を取るのがややむずかしそう？どうしたものか…

2023-06-24 19:10 UTC, Hourier commented on src/market/play-gamble.cpp
> +        msg_format(_("%dゴールドだけ受けよう。残りは取っときな。", "I'll take %d gold of that. Keep the rest."), maxbet);
arena.cpp も同じ状態なので削除しました
(強力発動コピペの嵐……)

2023-06-24 19:14 UTC, Hourier commented
input\_numerics() にオプション引数を足して弄れば何とかなりそうは気はします
(とはいえ0が必要なのはデバッグ周りだけと思われるので、そんなことのために設計の複雑度を増すのも悩ましいです。。。)

2023-06-24 19:17 UTC, habu1010 commented
コマンドを実行したら最初に「地上に戻りますか？」を表示し、yなら地上にジャンプ、nなら階層を選ぶ、という感じにしてしまうのはどうでしょうか。
1ステップ増えますが、デバッグコマンドだしそんなに頻繁に使用するものでもないのでそれでよいように思います。（地上にいる時は最初のチェックは省くくらいの親切さはあってもよいかも）

2023-06-24 19:23 UTC, Hourier commented
その方針で特に異論なしです、やってみます
逆に、1Fがあるダンジョンへ飛ぶ時も省略できると思います
コミットは分けておきます

2023-06-24 20:17 UTC, Hourier commented
上記対応しました
地上→鉄獄→鉄獄→イーク→イーク→オーク→オーク→地上 と周回してみましたが、ちゃんと必要な場合にのみ地上へ移動するかどうか聞かれました

これに関連して、select\_debugging\_dungeon() のcommand\_arg (最初のif)で戻り値がbool のままだったのでshort を返すように差し替えました

2023-06-25 00:59 UTC, habu1010 reviewed
デバッグコマンドのフロアジャンプを試してみましたが、地上に出る選択肢が意図通りでてこないようです。
（一応、ダンジョンID1（鉄獄）を指定→0階を指定すれば出られます。）

また、1Fのあるフロアは0階を選べる（そして地上選択がスキップされる）という仕様は不必要に複雑なので個人的には鉄獄も地上選択[y/n] or 1-127階でいいと思います。

それからコードを1箇所追加コメントしました。

2023-06-25 00:59 UTC, habu1010 commented on src/cmd-io/cmd-lore.cpp
> +            if (str_find(temp2, temp) || str_find(r_ref.name.data(), temp))
r_ref.name をそのまま渡せばよいです。（r_ref.name.data()を渡すと同じ文字列を持つstringオブジェクトを無駄に複製してしまう）

2023-06-25 01:07 UTC, habu1010 commented
いま再度検証していたところ、指定したダンジョンIDが今いるダンジョンと一緒なら地上に出る選択肢が表示されるという仕様であることがわかりました。
今の仕様でも理解すれば分からないことはないですが、

- （ダンジョンにいるなら地上に出るかの選択、yなら地上に戻る）→　ダンジョンID・階層選択

のほうが直感的のように個人的には思います。

2023-06-25 02:26 UTC, Hourier commented
.data() が残っていた箇所は修正してforce push しました
地上へ戻る選択肢については、個人的にはデバッグプレイ中に結構あちこち飛び回る (事前調査も含)ので、多少複雑度が上がっても旧来の仕様を残せそうなところは残したいなという印象です

2023-06-25 02:36 UTC, habu1010 commented
ステップが多くなるのが問題なのであれば、こうするのはどうでしょうか。

最初からダンジョンID→階層選択の流れをおこない、ダンジョンID選択でESCによりキャンセルしたら地上に戻るかどうかの選択肢を出す

これなら不自然さは減じますし、入力ステップも現在のダンジョン内での階層移動の場合3から2に減ります。

2023-06-25 03:03 UTC, Hourier commented
上記方針で賛成です！
修正してforce pushしました

2023-06-25 03:11 UTC, habu1010 approved these changes
想定通りの動作になっているのを確認しました。
追加のコメントはありませんのでApproveします。対応お疲れ様でした。

2023-06-25 03:12 UTC, merged

2023-06-25 03:12 UTC, Hourier commented
長らくの確認ありがとうございました！