静的解析警告の解消 その11
hengband/hengband pull request #3506
Opened 2023-07-04 13:06 UTC by Hourier

askfor() の周辺コード整備です
これ自体のシグネチャ変更が激重なのでその準備も兼ねています
怪しそうなファイル閲覧・マクロ登録＆実行・ダンプ書き出しは成功しました
ご確認下さい

2023-07-04 13:06 UTC, Hourier commented
以下のコミットは単純置換なので、置換した後の関数名だけチェックして下さい
dbc422f5bc359b696fac69534115bfd5ab57b2ae

2023-07-04 15:05 UTC, habu1010 requested changes
一通りチェックしてコメントしました。
それから、レビューの負担を減らすためIDEによる単純な置換はそれだけのPRを作ったほうがいいように思います。置換の名称が妥当であればすべて見るまでもなくApproveできます。
たとえ単純な置換のコミットを分けていても、PRの中では変更ファイル単位でしか「Viewed」をチェックできないので、結局すべての変更点を見る羽目になってしまいます。

2023-07-04 15:05 UTC, habu1010 commented on src/cmd-io/cmd-dump.cpp
> +                auto ch = inkey();
ESCAPEでwhileループから抜けられなくなっているのではないでしょうか？

2023-07-05 13:41 UTC, Hourier commented
修正してforce pushしました
単純置換については考慮に入れておきます

2023-07-06 13:02 UTC, Hourier commented on src/core/asking-player.cpp
> +    const auto input_amount = input_string(prompt, 6, "1");
NumLock がONの時もOFFの時も、テンキー入力でカーソルが動きました
ここは問題なさそうです

2023-07-06 13:04 UTC, habu1010 commented on src/core/asking-player.cpp
> +    const auto input_amount = input_string(prompt, 6, "1");
逆で、元の仕様を維持するならテンキー入力で数値が入力できないといけないと思います。
（数値を入力させる処理なので、それが自然だということでしょう）

2023-07-06 13:22 UTC, habu1010 approved these changes
数値を入力するシーンでテンキーをカーソルではなく数値入力として使うようにする件は input_integer も含めて別Issueとして解決するということなので、本PRはApproveします。

2023-07-06 13:32 UTC, merged

2023-07-06 13:32 UTC, Hourier commented
確認ありがとうございました！
数値入力の件は#3514 にて対応します