[Fix] 打撃回避判定のバグ修正
hengband/hengband pull request #36
Opened 2021-02-09 23:49 UTC by taotao54321

Fixes #21.

`check_hit_from_monster_to_player()` が偽を返したときに回避時の処理を行うべきだが、そうなっていなかった。
本修正により、打撃をかわしたときに盾技能が成長するようになる。以前は打撃を食らったときに盾技能が成長していた。

2021-02-11 06:54 UTC, habu1010 commented
現状だと攻撃を回避した時に、increase_blow_type_seen(モンスターの攻撃に関する知識の蓄積)、check_fall_off_horse(落馬判定)、変わり身の術の発動が行われてしまうようですが、大丈夫なのでしょうか？
これらは攻撃がヒットした時だけ行うべき処理のような気がします。

2021-02-11 15:08 UTC, taotao54321 commented
ありがとうございます。Discord での議論も踏まえ、落馬/変わり身の処理は命中時のみ行うように、思い出処理は従来通り常時行うこととしました。

2021-02-11 17:02 UTC, taotao54321 commented on src/monster-attack/monster-attack-player.c
> +
ありがとうございます。`increase_blow_type_seen()` を命中処理および回避処理の直後にそれぞれ呼び出すように修正しました。

2021-02-12 09:57 UTC, habu1010 submitted a review, later dismissed
process_monster_blows内でステップ実行して、動作OKであることを確認しました。
お疲れさまでした。

2021-02-12 10:29 UTC, Hourier requested changes
process_monster_attack_hit() の返り値 (v2.2.1までは、対邪悪結界が有効だと攻撃が当たっていないことになる)が無視されていますが、問題ないでしょうか？
この修正コードだと、対邪悪結界が張られていても落馬処理が発生しうるように見えます
後ほど私自身が再修正したコードをアップしますので、比較お願いします
(一旦マージはブロックしておきます)

2021-02-12 13:03 UTC, taotao54321 commented
@Hourier
ありがとうございます。
仰る通り、対邪悪結界で撃退した場合は別に処理する必要がありますね。
v2.2.1 の仕様では、このケースは思い出なども含めて一切の処理を行わず次の打撃へ移行するとなっていたので、とりあえずそれを踏襲しようと思います。

なお、feature/Fix-Monster-Attack-Evasion のコードでは(対邪悪結界なしで)回避した場合に思い出処理がなされないのが気になりました。

ひとまずこちらでは対邪悪結界の件のみ修正して push しておきます。

2021-02-12 13:53 UTC, taotao54321 commented
#21 での議論も踏まえ、撃退時は思い出処理のみ行う形で修正しました。

2021-02-12 14:39 UTC, habu1010 approved these changes
紆余曲折ありましたが、最終的に固まった仕様で動作しているのをステップ実行で確認しました。

2021-02-12 14:42 UTC, Hourier approved these changes
再確認しました
仕様通りのコードになっていると思います
対応ありがとうございました

2021-02-12 14:43 UTC, merged