AngbandSystem クラスを作成し、phase_out フィールドをPlayerType から移した
hengband/hengband pull request #3666
Opened 2023-10-16 14:04 UTC by Hourier

※ 周辺コードも含めて変更量が莫大なので注意

PlayerType に所属していることで10個以上の関数から依存性が発生していた箇所を修正しました
これにより各種モデルクラスへのメソッド繰り込みが実現できました
シングルトンの扱いには別途議論 (#3654)がありますが、議論発生前から作業していたものなので修正はこのPRがマージされた後で行います

2023-10-17 03:38 UTC, sikabane-works commented
申し訳ない、フェイズ・アウトってのは私が旧ソース名から付けなおしたのですが、MtGのキーワードで平たく言って「その場にいないように扱う」という意味でした。
一般性がないと言えばその通りなのですが、何でもちゃんぽんする世界観のゲーム中の用語としてはできれば残していただきたいかなと思っております。

2023-10-17 03:52 UTC, Hourier commented
承知しました
が、変数名を遡って改名すると非常にrebase負荷が高い (実際高かった)ので、修正コミット一つ積みます

2023-10-17 03:54 UTC, sikabane-works commented
すみません、それでよろしくお願いします。キーワードについては、紛らわしいのは確かなので、別個どこかに補足記します。

2023-10-17 11:39 UTC, Hourier commented
修正完了しました
改めてご確認下さい

2023-10-20 03:28 UTC, habu1010 reviewed
全部チェックするのは厳しいので、とりあえずメンバ関数化した部分に関して1つコメントしました。

2023-10-20 03:28 UTC, habu1010 commented on src/system/floor-type-definition.h
> +    bool has_los_bold(const Pos2D pos);
constメンバ関数にするべきです。
おそらく内部で get_grid を呼び出しているから const を付けるとコンパイルエラーになるので付けていないのだと思いますが、

```c++
const grid_type &get_grid(const Pos2D pos) const;
```

（コードは非const版と全く同じ）を追加実装すればよいです。

また、constメンバ関数にすることにより、現在 has_los_bold を呼び出しているため const 参照にできてない変数を多数 const 参照にできると思われます。

2023-10-21 01:06 UTC, Hourier commented on src/system/floor-type-definition.h
> +    bool has_los_bold(const Pos2D pos);
修正完了しました、コメントありがとうございます (まさにやりたかったことです！)
かなりの箇所がconstになってコードの扱いやすさが向上しました
get\_apprearance\_monrace() の修正もrebase しました
ご確認下さい

2023-10-28 10:00 UTC, Hourier commented
コンパイルエラーが無事修正されました
改めてご確認下さい

2023-10-29 08:32 UTC, sikabane-works requested changes
１か所問題と判断した場所みつけましたのでよろしくお願いします。

2023-10-29 08:59 UTC, Hourier commented on src/monster/monster-status-setter.cpp
> +    should_output_message = projectable(player_ptr, player_ptr->y, player_ptr->x, m_ptr->fy, m_ptr->fx);
確認ありがとうございます
修正してforce pushしました

2023-10-29 09:12 UTC, sikabane-works approved these changes
お疲れ様でした。Approveします。

2023-10-29 09:16 UTC, merged

2023-10-29 09:16 UTC, Hourier commented
確認ありがとうございました！