[Feature] ArtifactDefinitionsのJSON化
hengband/hengband pull request #4078
Opened 2024-05-15 08:00 UTC by dis-

設定ファイルのJSON化を進める。合わせて読込部分の修正、schemaの作成を実施する。

2024-05-15 10:21 UTC, Hourier commented on src/info-reader/artifact-reader.cpp
> +    const auto base_ac = ac_data.get<int>();
(できるか分かりませんが)ここのキャストをshort にすれば下のARMOUR\_CLASS へのキャストは不要になるのではないでしょうか？
不可能な場合、下のキャストは「static\_cast\<short\>」に変えて下さい (型エイリアスは廃止方針のためなるべく減らしたい)
set\_art\_to\_ac() も同様です

2024-05-15 11:05 UTC, dis- commented on src/info-reader/artifact-reader.cpp
> +    const auto base_ac = ac_data.get<ARMOUR_CLASS>();
型エイリアス不要な形に修正しました。

2024-05-15 12:07 UTC, Hourier reviewed
追加で3箇所コメントしました
ご確認下さい

2024-05-15 12:07 UTC, Hourier commented on src/info-reader/artifact-reader.cpp
> +    const auto base_ac = ac_data.get<ARMOUR_CLASS>();
ここは\<short\> に置き換えて下さい

2024-05-15 12:07 UTC, Hourier commented on src/info-reader/artifact-reader.cpp
> +    const auto to_ac = to_ac_data.get<ARMOUR_CLASS>();
\<short\> に置き換えて下さい

2024-05-15 12:46 UTC, dis- commented
修正しました

2024-05-15 12:55 UTC, Hourier commented
対応ありがとうございました
ひとまずC++のコード面は私からは以上です

2024-05-17 11:47 UTC, habu1010 reviewed
コードについて1点だけコメントしました。

2024-05-17 11:47 UTC, habu1010 commented on src/info-reader/artifact-reader.cpp
> +    artifact.name = ja_name_sys.value();
この部分ですが、

```c++
    auto ja_name_sys = utf8_to_sys(ja_name->get<std::string>());
    if (!ja_name_sys) {
        return PARSE_ERROR_INVALID_FLAG;
    }
    artifact.name = std::move(*ja_name_sys);
```

とすることで、文字列全体のコピーの代わりに、文字列があるヒープへのポインタの書き換えになるはずなので、若干効率的になるかと思います。flavor側も同様。注意点として、上記のように変数は非constにしておかないとmoveできません。（constなので当然なのですが警告もなにも出ないので間違いやすい）
なお、optionalの値を取り出すときはなるべく value() ではなく operator* を使用する方針です。（絶対ではないですが）

2024-05-18 10:42 UTC, dis- commented on src/info-reader/artifact-reader.cpp
> +    artifact.name = ja_name_sys.value();
該当箇所を修正しました。

2024-05-18 12:20 UTC, habu1010 submitted a review, later dismissed
修正確認しましたのでApproveします。

2024-05-18 12:23 UTC, Hourier requested changes
これを実施して下さい
https://github.com/hengband/hengband/pull/4048/files

2024-05-18 12:43 UTC, dis- commented
Makefileへの追加対応しました

2024-05-18 12:45 UTC, Hourier approved these changes
対応お疲れ様です
Approveします

2024-05-18 12:57 UTC, dis- commented
確認ありがとうございました

2024-05-18 12:57 UTC, merged