wr_monster() とその下の関数を MonsterEntity 内のメソッドにした
hengband/hengband pull request #4202
Opened 2024-06-02 15:59 UTC by Slimebreath6078

Close #4197

2024-06-02 21:50 UTC, Hourier requested changes
対応お疲れ様です
せっかく実施して頂いたところ悪いのですが、既存クラスにセーブデータへの読み書き責務を追加するのは単一責任原則に反してしまいます
これをマージするのは難しいです

2024-06-03 00:43 UTC, Hourier commented
補足：「モンスター実体情報をセーブデータに書く/読む」という責務のクラスを1つ作ってそこへまとめていくのは賛成です
(単なる設定ファイルよりは重たいので、読み書きで別々の責務を持たせた方が今回はベターかと思います。fstreamに変えるとなると色々面倒な気配はしますが詳細は別途相談で)

2024-06-03 22:32 UTC, Slimebreath6078 commented
MonsterEntity クラスに直接移植するのではなく新たにFriendで関連付けたクラスを作り、そこに移植しました
ご確認お願いいたします

2024-06-04 16:46 UTC, Slimebreath6078 commented
一度統合した関数移植とファイル名変更のコミットを再び分けました

2024-06-08 01:32 UTC, Hourier reviewed
対応お疲れ様です
何点かコメントしました
コーディング規約の話もあるので、詳細はDiscord でどうすべきか詰めたいです
ご確認下さい

2024-06-08 01:32 UTC, Hourier commented on src/save/monster-entity-writer.h
> +#include "util/flag-group.h"
このインクルードは不要です

2024-06-08 01:32 UTC, Hourier commented on src/save/monster-entity-writer.h
> +    BIT_FLAGS write_monster_flags() const;
ファイルへの読み書きはuint32\_t で行いましょう
(\<cstdint\> をインクルードして下さい)

2024-06-08 01:32 UTC, Hourier commented on src/save/monster-entity-writer.h
> +    MonsterEntityWriter() = delete;
引数つきコンストラクタだけが定義されていればデフォルトコンストラクタは暗黙的に削除されます
(MSVCも特に警告出しません)

2024-06-08 01:32 UTC, Hourier commented on src/system/monster-entity.h
> +    friend class MonsterEntityWriter;
変愚のコードでは前例がないですが、個人的にはフレンド宣言は (コンストラクタよりも)先頭に置いた方がいいのかな？
という感じがします

2024-06-23 07:24 UTC, Slimebreath6078 reviewed
ご指摘いただいた内容を修正いたしました
ご確認ありがとうございました

2024-06-23 07:24 UTC, Slimebreath6078 commented on src/save/monster-entity-writer.h
> +#include "util/flag-group.h"
削除して`<cstdint>`をインクルードしました

2024-06-23 07:24 UTC, Slimebreath6078 commented on src/save/monster-entity-writer.h
> +    BIT_FLAGS write_monster_flags() const;
定義部分も含めて`uint32_t`に変えました

2024-06-23 07:24 UTC, Slimebreath6078 commented on src/save/monster-entity-writer.h
> +    MonsterEntityWriter() = delete;
こちらでも警告が特に発生しなかったのとDiscordでの協議を踏まえてデフォルトコンストラクタの明示削除を消しました

2024-06-23 07:24 UTC, Slimebreath6078 commented on src/system/monster-entity.h
> +    friend class MonsterEntityWriter;
Google C++ Style Guide にfriend にする型の宣言はセクションの先頭に置くと書かれていること、それに合わせない理由も特にないため先頭に置きました

2024-08-03 01:48 UTC, Hourier approved these changes
対応お疲れ様でした
確認遅れてすみません
Approveします

2024-08-03 02:09 UTC, Slimebreath6078 commented
ご確認ありがとうございました

2024-08-03 02:09 UTC, merged