[Featire] 通常エゴと呪いエゴの選出ルーチンを変更
hengband/hengband pull request #483
Opened 2021-03-12 11:49 UTC by iks3

通常エゴには呪いが付加されるエゴを選出いない(悪魔など)
呪いエゴにはレーティングが0または呪いが付加されるエゴを選出(悪魔など)

#325のようなエゴに対応できるように前準備として。
また、高級品確定ドロップで呪いエゴが落ちるのは序盤厳しいという意見もあるので。

2021-03-12 12:29 UTC, sikabane-works approved these changes
ペナルティのアルタイプのエゴが生成されなくなるのを確認できました。Approveします。

2021-03-12 16:24 UTC, iks3 commented
判定の条件式をシンプルに書き直しましたので、再確認お願いします。

2021-03-13 11:33 UTC, iks3 commented
gen_flagsのFlagGroup化を先にプルリクしますので、一旦保留で。

2021-03-13 13:46 UTC, sikabane-works approved these changes
悪魔とモルグルの呪い不可をpower<-1に回したということを再確認しました。Approveします。

2021-03-13 15:17 UTC, iks3 commented
#489の修正後のdevelopにrebaseして再コミットしました。
確認お願いします。

2021-03-13 15:47 UTC, sikabane-works requested changes
デバッグモードでworthless生成を頭防具や体防具にかけても悪魔エゴが出なかったり、生成ミスって無限ループになっている気がします。確認いただけると幸いです。

2021-03-13 15:55 UTC, sikabane-works approved these changes
pullしなおしたら正しく動作しました。Approveします。

2021-03-13 15:55 UTC, merged