[Feature] オプションのデフォルト値を変更
hengband/hengband pull request #822
Opened 2021-04-17 18:15 UTC by iks3

最初からオンでよさそうなものをオンに。

2021-04-17 20:44 UTC, shimitei requested changes
#755 でpref-opt.prfに記載漏れとあるオプションのうち、keep_savefileは未だ記載されていません。
また、easy_floorオプションはpref-opt.prfではY、コードではFALSEと設定の食い違いがあります。

### pref-opt.prfの記載漏れ対応
- [x] skip_more default:X
- [x] view_hidden_walls default:X->Y
- [x] view_unsafe_walls default:Y->X
- [x] fresh_once default:X
- [x] show_ammo_detail default:Y
- [x] show_ammo_no_crit default:X
- [x] show_ammo_crit_ratio default:X
- [x] show_actual_value default:X->Y
- [x] allow_debug_opts default:X　※漏れてないpref-opt.prfに存在する
- [ ] keep_savefile default:Y

### Y(TRUE)に変更
- [x] display_path .prf:Y
- [x] display_path .cpp:Y
- [x] view_unsafe_grids .prf:Y
- [x] view_unsafe_grids .cpp:Y
- [x] alert_trap_detect .prf:Y
- [x] alert_trap_detect .cpp:Y　※元からTRUE
- [x] easy_floor .prf:Y
- [ ] easy_floor .cpp:Y
- [x] abbrev_all .prf:Y
- [x] abbrev_all .cpp:Y
- [x] bound_walls_perm .prf:Y
- [x] bound_walls_perm .cpp:Y　※元からTRUE
- [x] show_actual_value .prf:Y
- [x] show_actual_value .cpp:Y

2021-04-18 04:20 UTC, iks3 commented
修正しました。

2021-04-18 04:24 UTC, shimitei approved these changes

2021-04-18 04:24 UTC, merged

2021-04-18 04:24 UTC, shimitei commented
OKです。