[Feature] Windows版で画面描画のちらつき等を抑える
hengband/hengband pull request #892
Opened 2021-04-23 20:20 UTC by iks3

Termごとにビットマップを所持してダブルバッファリングで表示をする。
非表示のTermでもビットマップを所持している、デスクトップサイズで所持しているなど改善点があるのでドラフト。

また、news_j.txtの表示～読み込みメッセージまでの間が表示されないようなので、そこも確認したい。

2021-04-24 09:19 UTC, shimitei commented
term_text_win関数の
```
    if (initialized)
        InvalidateRect(td->w, NULL, FALSE);
    else {
        td->update_hdc();
        ValidateRect(td->w, NULL);
    }
```
の部分を以下のようにするとタイトル画面の初期化中メッセージが表示されるようになりました。
```
    if (initialized)
        InvalidateRect(td->w, NULL, FALSE);
    else {
        td->update_hdc();
        InvalidateRect(td->w, NULL, FALSE);
    }

```

2021-04-24 17:29 UTC, iks3 commented
出来たと思いますので、Ready for Reviewします。

2021-04-25 00:21 UTC, shimitei submitted a review, later dismissed
タイル表示も描画が速くなりました。
おおむね問題なく、強いて言えばRコマンドでの時間経過がゆっくりになる点がタイムアタック勢には不評かもしれません。
Approveします。

2021-04-25 12:08 UTC, iks3 commented
余計な描画をしないよう修正しているときに気が付きましたが、ボールやボルトなどの表示が処理が終わるまでされないようのですので一旦保留します。

2021-04-25 14:06 UTC, Hourier requested changes
誤マージ防止のため一旦ブロックしておきます

2021-04-29 08:25 UTC, shimitei commented
「魔法や矢の軌跡を表示する」はディレイ処理を通ってるはずなので、そこで再描画するのはどうでしょうか。
```
static int term_xtra_win_delay(int v)
{
    Sleep(v);
    UpdateWindow(data[0].w); // 追加
    return 0;
}

```

2021-04-29 08:28 UTC, iks3 commented
> static int term_xtra_win_delay(int v)

この関数の存在をすっかり見落としていました。

2021-04-29 15:09 UTC, closed without merging