Include system/h-basic.h in target/target-setter.h
hengband/hengband pull request #982
Opened 2021-04-30 03:20 UTC by backwardsEric

That avoids a compiler error when compiling target/target-setter.cpp with Ubuntu 20.04's default g++ and no precompiled headers.  The error was "found ':' in nested-name-specifier, expected '::'" when compiling "enum target_type : uint8_t;", presumably because the compiler didn't recognize uint8_t as something appropriate for setting the size of the enum.

2021-04-30 10:07 UTC, Hourier requested changes
Now reviewing this pull request among dev team in Japan.
Please wait for a while.

2021-04-30 15:46 UTC, backwardsEric commented
If my description of the compiler error was unclear, here's an example of the error when compiling without precompiled headers:  https://github.com/backwardsEric/hengband/runs/2471991901?check_suite_focus=true

2021-05-01 14:45 UTC, iks3 commented
We need including a header cstdint or a header including it for using uint8_t,
on the other hand, carelessly including headers sometimes causes some warings or errors.

So, to solve this, please change 'uint8_t' to 'unsigned int' in follows:

- src/target/target-describer.h
- src/target/target-setter.h
- src/target/target-types.h

2021-05-01 15:20 UTC, backwardsEric commented
The requested changes were force pushed as the only commit.

2021-05-01 15:24 UTC, iks3 approved these changes
Thank you for the quick response.

2021-05-01 15:27 UTC, merged